---
title: "PD_Fingerprinting"
---

```{r read in data & check for demo diff between groups}
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library("ggpubr")
library(BayesFactor)
library(corrplot)
library(ggseg)

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

data %>% group_by(Group) %>% summarise(m_age= mean(Age, na.rm=TRUE), sd_age= sd(Age, na.rm=TRUE))
table(data$Group, data$Sex)
table(data$Group, data$Handedness)

data %>% group_by(Group) %>% summarise(m_age= mean(Education_coded, na.rm=TRUE), sd_age= sd(Education_coded, na.rm=TRUE))

data %>% group_by(Group) %>% summarise(m_age= mean(Hoehn.and.Yahr.score, na.rm=TRUE), sd_age= sd(Hoehn.and.Yahr.score, na.rm=TRUE))

data %>% group_by(Group) %>% summarise(m_age= mean(updrs2, na.rm=TRUE), sd_age= sd(updrs2, na.rm=TRUE))

data %>% group_by(Group) %>% summarise(m_age= mean(moca2, na.rm=TRUE), sd_age= sd(moca2, na.rm=TRUE))

# look for diff between gruops
t.test(data$Age[data$Group== 'Control'],data$Age[data$Group== 'Parkinson'])
sd(data$Age[data$Group== 'Control'])
t.test(data$Education_coded[data$Group== 'Control'],data$Education_coded[data$Group== 'Parkinson'])
sd(data$Education_coded[data$Group== 'Control'])

contingency_tab=table(data$Group, data$Sex)

chisq.test(contingency_tab[1:2,2:3], simulate.p.value = TRUE)

contingency_tab=table(data$Group, data$Handedness)

chisq.test(contingency_tab[1:2,3:4], simulate.p.value = TRUE)

t.test(data$recording_length[data$Group =='Control'], data$recording_length[data$Group =='Parkinson'])

t.test(data$identifiability[data$Handedness =='R'], data$identifiability[data$Handedness !='R'])


# add in CamCan info
demo=read.csv('~/Documents/CAMCAN_outputs/CAMCAN_Analysis/standard_data.csv')
demo$CCID=paste('sub',demo$CCID, sep = '_')
ids=read.csv('~/Documents/CAMCAN_outputs/CAMCAN_Analysis/subject_codes.csv')
index=demo$CCID %in% ids$Ids
demo=demo[index,]

full_demo=read.csv('~/Documents/CAMCAN_outputs/approved_data.csv')
full_demo$CCID=paste('sub',full_demo$CCID, sep = '_')
index=full_demo$CCID %in% ids$Ids
full_demo=full_demo[index,]

index_age= demo$Age >= 40 & demo$Age <= 78
full_demo=full_demo[index_age,]

demo$Sex[index_age]

# compute SMD for the control samples 
# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3144483/#s11title
(64.63-44.45)/sqrt(((8.66^2) + (20.95^2)/2)) # PRE OMEGA
(64.63-61.98)/sqrt(((8.66^2) + (8.89^2)/2)) # POST OMAGE

# sex
(0.29-0.57)/ sqrt(((0.29*0.71) + (0.42*0.57)/2)) # PRE
(0.29-0.44)/ sqrt(((0.29*0.71) + (0.44*0.56)/2)) # POST

# hand
(0.85-0.92)/ sqrt(((0.85*0.15) + (0.92*0.08)/2)) # PRE
(0.85-0.89)/ sqrt(((0.85*0.15) + (0.89*0.11)/2)) # POST

# Education
(15.28-16.2)/sqrt(((3.30^2) + (3.57^2)/2)) # PRE OMEGA
(15.28-15.53)/sqrt(((3.30^2) + (3.57^2)/2)) # POST OMAGE

# age
(64.63-54.69)/sqrt((8.66^2 + 18.28^2)/2) # PRE Cam-CAN
(64.63-58.67)/sqrt((8.66^2 + 11.04^2)/2) # POST Cam-CAN

#sex
(0.29-0.49)/ sqrt(((0.29*0.71) + (0.49*0.51)/2)) # PRE
(0.29-0.5)/ sqrt(((0.29*0.71) + (0.5*0.5)/2)) # POST

# hand
(0.85-0.89)/ sqrt(((0.85*0.15) + (0.89*0.11)/2)) # PRE
(0.85-0.89)/ sqrt(((0.85*0.15) + (0.89*0.11)/2)) # POST


```




```{r plot fingerprinting accuracy}
# get accuracy and plot (see python scripts for how we computed the differentiation accuracy)

# plot fingerprinting accuracy for all conditions (differentiation accuracy)
df=read.csv("~/Documents/PD_fingerprinting/new_analysis_Nov2022/fullband_fingerpritninf.csv", header = TRUE, stringsAsFactors = FALSE)
df$Experiment= factor(df$Experiment,levels = c("CTL", "PD",'PDvsHC'))
df$Band= factor(df$Band,levels = c("fullband"))
df$Band=plyr::mapvalues(df$Band, unique(df$Band), c("broadband"))

ggplot(data=df, aes(x=Band, y=ACC_boot, fill=Experiment, width=.5)) +  coord_cartesian(ylim=c(0,100))+geom_bar(stat = "identity", position=position_dodge(width = 0.5)) +
geom_errorbar(aes(ymin=ACC_lowerCI, ymax=ACC_upperCI), width=.2 ,position=position_dodge(.5)) +theme_classic2() + scale_fill_manual(values=cbbPalette) + labs(y="Accuracy (%)", x="",title="") + theme(text = element_text(size=35), legend.title=element_blank())

ggsave('~/Documents/PD_fingerprinting/figure/fingerprinting_cohort_new_all.pdf', device = "pdf", width=8, height=8, dpi=800)


# PLOT APERIODIC and aperiodic corrected accuracy
df=read.csv("~/Documents/PD_fingerprinting/fingerprinting_accuracy_aperiodic.csv", header = TRUE, stringsAsFactors = FALSE)
df$Experiment= factor(df$Experiment,levels = c("CTL", "PD",'PDvsHC'))
df$Band= factor(df$Band,levels = c("fullband", 'aperiodic', 'aperiodic corrected'))
df$Band=plyr::mapvalues(df$Band, unique(df$Band), c("broadband", 'aperiodic', 'aperiodic corrected'))

ggplot(data=df, aes(x=Band, y=ACC_boot, fill=Experiment, width=.5)) +  coord_cartesian(ylim=c(0,100))+geom_bar(stat = "identity", position=position_dodge(width = 0.5)) +
geom_errorbar(aes(ymin=ACC_lowerCI, ymax=ACC_upperCI), width=.2 ,position=position_dodge(.5)) +theme_classic2() + scale_fill_manual(values=cbbPalette) + labs(y="Accuracy (%)", x="",title="") + theme(text = element_text(size=35), legend.title=element_blank())

ggsave('~/Documents/PD_fingerprinting/figure/fingerprinting_cohort_new_aperiodic.pdf', device = "pdf", width=12, height=8, dpi=800)


# PLOT EMPTY ROOM accuracy
df=read.csv("~/Documents/PD_fingerprinting/emptyroom_fingerpritning.csv", header = TRUE, stringsAsFactors = FALSE)
df$Experiment= factor(df$Experiment,levels = c("CTL", "PD",'PDvsHC'))

ggplot(data=df, aes(x=Band, y=ACC, fill=Experiment, width=.5)) +  coord_cartesian(ylim=c(0,100))+geom_bar(stat = "identity", position=position_dodge(width = 0.5)) +
 theme_classic2() + scale_fill_manual(values=cbbPalette) + labs(y="Accuracy (%)", x="",title="") + theme(text = element_text(size=35), legend.title=element_blank()) + scale_fill_grey()

ggsave('~/Documents/PD_fingerprinting/figure/fingerprinting_emptyroom.pdf', device = "pdf", width=8, height=8, dpi=800)

```


```{r self and other similarity full spectrum}

# read data
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

# read e phys
target= read.csv('~/Documents/Alex_fingerprinting/NEW_features_4_fingeprinting_target.csv', header = FALSE)

database= read.csv('~/Documents/Alex_fingerprinting/NEW_features_4_fingeprinting_database.csv', header = FALSE)

# remove sub ID and col/ row names etc 
target=target[-1,- length(target)]
database=database[-1,- length(target)]

target=target[,-1]
database=database[,-1]

# remove excluded subjects based on too short of recordings
data2=read.csv('/Users/jason/Documents/Alex_fingerprinting/auto_cross_corrs.csv')

# keep pnly participants with two recordings!!!! Min 10 minutes total
# this is importnat for the self-similarity over gap durations 
# i.e., 30 second fingerprints 
target= target[data2$recording_length > 50, ]
database= database[data2$recording_length > 50, ]

# broadband  self similarity 
corr_bb=cor(t(database),t(target)) 
self_corrbb=diag(corr_bb) # diag elements is self-sim

# compute acc to check if the same as python
tt=apply(corr_bb, 1, which.max)
sum(seq(1,133)==tt)/133

tt=apply(corr_bb, 2, which.max)
sum(seq(1,133)==tt)/133

# plot hist 
hist(self_corrbb[1:54])
hist(self_corrbb[54:133])

mean(self_corrbb[1:54])
mean(self_corrbb[55:133])

# do self-similarity differ between groups?
# permutation t-test 
RVAideMemoire::perm.t.test(DescTools::FisherZ(self_corrbb[1:54]),DescTools::FisherZ(self_corrbb[55:133]), nperm=1000)

# plot self-similarity effects (broadband)
data4plot= data.frame(corrs= c(self_corrbb[1:54],self_corrbb[55:133]), group= c(rep('Controls', 54),rep('Parkinson', 79)))

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

ggplot(data4plot, aes(corrs, color= group, fill=group, alpha=0.5)) +
  geom_density(aes( color= group, fill=group), alpha= 0.5) +
  #geom_histogram(aes(y=..density.., color= group, fill=group), alpha= 0.5, bins = 20) +
  theme_minimal() +
  labs(x = "self correlation", y = "denstity")  + theme_classic2() +
  ggtitle("") + scale_fill_manual(values=cbbPalette[c(1,3)]) + scale_color_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/hist_of_self_corr_broadband.pdf', device = "pdf")

# now let us look at other-similarity
newcorr_bb= corr_bb
diag(newcorr_bb) = NA

data4plot= data.frame(corrs= c(newcorr_bb[1:54, 1:54],newcorr_bb[55:133, 55:133]), group= c(rep('Controls', 54*54),rep('Parkinson', 79*79)) )

ggplot(data4plot, aes(corrs, color= group, fill=group, alpha=0.5)) +
  geom_density(aes( color= group, fill=group), alpha= 0.5, bins = 20) +
  theme_minimal() +
  labs(x = "correlation to others in cohort", y = "denstity")  + theme_classic2() +
  ggtitle("") + scale_fill_manual(values=cbbPalette[c(1,3)]) + scale_color_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/hist_of_other_corr_delta.pdf', device = "pdf")


newcorr_bb= corr_bb
diag(newcorr_bb) = NA
cross_corr= c(rowMeans(newcorr_bb[1:54,1:54], na.rm= TRUE), rowMeans(newcorr_bb[55:133,55:133], na.rm= TRUE))


mean(rowMeans(cbind(rowMeans(newcorr_bb[55:133,1:54], na.rm= TRUE),colMeans(newcorr_bb[1:54,55:133], na.rm= TRUE))))

sd(rowMeans(cbind(rowMeans(newcorr_bb[55:133,1:54], na.rm= TRUE),colMeans(newcorr_bb[1:54,55:133], na.rm= TRUE))))


data4plot= data.frame(corrs= cross_corr, group= c(rep('Controls', 54),rep('Parkinson', 79)) )

data4plot=na.omit(data4plot)
ggplot(data=data4plot, aes(x=group, y=corrs, colour=group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.5) + stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="cross-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.position = 'none', legend.title=element_blank()) + coord_cartesian(ylim = c(0.37, 0.5)) + scale_color_manual(values=cbbPalette[c(1,2,3)]) + scale_fill_manual(values=cbbPalette[c(1,2,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/LONG_crosscorr_.pdf', device = "pdf", width=8, height=8, dpi=800)


```


```{r self and other similarity ar-rhythmic }

## repeat same process for arrhythmic and rhythmic features
target= read.csv('/Users/jason/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_target.csv', header = FALSE)

database= read.csv('/Users/jason/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_database.csv', header = FALSE)

target=target[-1,- length(target)]
database=database[-1,- length(target)]

target=target[,-1]
database=database[,-1]

corr_AP=cor(t(database),t(target)) 
self_corrAP=diag(corr_AP)

RVAideMemoire::perm.t.test(DescTools::FisherZ(self_corrAP[1:54]),DescTools::FisherZ(self_corrAP[55:133]), nperm=1000)


library(ggpubr)
data4plot= data.frame(corrs= c(self_corrAP[1:54],self_corrAP[55:133]), group= c(rep('Controls', 54),rep('Parkinson', 79)))

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

ggplot(data4plot, aes(corrs, color= group, fill=group, alpha=0.5)) +
  geom_density(aes( color= group, fill=group), alpha= 0.5, bins = 20) +
  #geom_histogram(aes(y=..density.., color= group, fill=group), alpha= 0.5, bins = 20) +
  theme_minimal() +
  labs(x = "self correlation", y = "denstity")  + theme_classic2() +
  ggtitle("") + scale_fill_manual(values=cbbPalette[c(1,3)]) + scale_color_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/hist_of_self_corr_aperiodic.pdf', device = "pdf")


# other similarity 
newcorr_bb= corr_AP
diag(newcorr_bb) = NA

data4plot= data.frame(corrs= c(newcorr_bb[1:54, 1:54],newcorr_bb[55:133, 55:133]), group= c(rep('Controls', 54*54),rep('Parkinson', 79*79)) )

ggplot(data4plot, aes(corrs, color= group, fill=group, alpha=0.5)) +
  geom_density(aes( color= group, fill=group), alpha= 0.5, bins = 20) +
  theme_minimal() +
  labs(x = "correlation to others in cohort", y = "denstity")  + theme_classic2() +
  ggtitle("") + scale_fill_manual(values=cbbPalette[c(1,3)]) + scale_color_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/hist_of_other_corr_aperiodic.pdf', device = "pdf")



## Now let us look at aperiodic corrected data
target= read.csv('/Users/jason/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_corrected_target.csv', header = FALSE)

database= read.csv('/Users/jason/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_corrected_database.csv', header = FALSE)

target=target[-1,- length(target)]
database=database[-1,- length(target)]

target=target[,-1]
database=database[,-1]

corr_APC=cor(t(database),t(target)) 
self_corrAPC=diag(corr_APC)

RVAideMemoire::perm.t.test(DescTools::FisherZ(self_corrAPC[1:54]),DescTools::FisherZ(self_corrAPC[55:133]), nperm=1000)



data4plot= data.frame(corrs= c(self_corrAPC[1:54],self_corrAPC[55:133]), group= c(rep('Controls', 54),rep('Parkinson', 79)))

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

ggplot(data4plot, aes(corrs, color= group, fill=group, alpha=0.5)) +
  geom_density(aes( color= group, fill=group), alpha= 0.5, bins = 20) +
  #geom_histogram(aes(y=..density.., color= group, fill=group), alpha= 0.5, bins = 20) +
  theme_minimal() +
  labs(x = "self correlation", y = "denstity")  + theme_classic2() +
  ggtitle("") + scale_fill_manual(values=cbbPalette[c(1,3)]) + scale_color_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/hist_of_self_corr_aperiodicCORRECTED.pdf', device = "pdf")



newcorr_bb= corr_APC
diag(newcorr_bb) = NA

data4plot= data.frame(corrs= c(newcorr_bb[1:54, 1:54],newcorr_bb[55:133, 55:133]), group= c(rep('Controls', 54*54),rep('Parkinson', 79*79)) )

ggplot(data4plot, aes(corrs, color= group, fill=group, alpha=0.5)) +
  geom_density(aes( color= group, fill=group), alpha= 0.5, bins = 20) +
  theme_minimal() +
  labs(x = "correlation to others in cohort", y = "denstity")  + theme_classic2() +
  ggtitle("") + scale_fill_manual(values=cbbPalette[c(1,3)]) + scale_color_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/hist_of_other_corr_aperiodicCORRECTED.pdf', device = "pdf")


```

```{r Plot example spectra fullband to visualize effects }

cbbPalette <- c( '#808080',"#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

target= read.csv('~/Documents/PD_fingerprinting/features_4_fingeprinting_target.csv' )

database= read.csv('~/Documents/PD_fingerprinting/features_4_fingeprinting_database.csv' )

target=target[,-1]
database=database[,-1]

roi_index= (451*(44-1)+1):(451*(44-1)+451) # select out ROI
# data organized in one large vectroized matrix where the spectra 1-150 Hz
# of each roi is stacked ->

target_LSP= target[,roi_index]
database_LSP= database[,roi_index]

target_LSP= (target_LSP+database_LSP)/2 # average two fingerprints for plot

target_LSP= cbind(data, stack(target_LSP))

target_LSP$ind = plyr::mapvalues(target_LSP$ind , unique(target_LSP$ind ), seq(0,150,1/3))

target_LSP$ind= as.numeric(as.character(target_LSP$ind))


data4plot= target_LSP %>% group_by(Group, ind) %>% summarise( power= mean(log(values)), SEM= (sd(log(values))/sqrt(n())))
data4plot= data4plot[!is.na(data4plot$Group),]

control= data4plot[data4plot$Group=='Control',]

ggplot(data4plot, aes(x= ind, y = power, fill= Group,colour= Group, ymin=power-SEM, ymax=power+SEM)) + geom_ribbon(alpha=0.5, colour= NA) + geom_line() + theme_classic2() + xlim(1,100) +  coord_cartesian(xlim = c(1, 40), ylim= c(-2,3.5) )

ggsave('~/Documents/PD_fingerprinting/figure/Spectrum_right_pericalcarine_group.pdf', device = "pdf", width=10, height=5, dpi=800)

target_LSP= target_LSP[target_LSP$Group== 'Parkinson', ]
target_LSP= target_LSP[!is.na(target_LSP$updrs2), ]
target_LSP= target_LSP[!is.na(target_LSP$moca2), ]
target_LSP$updrs2_binned=target_LSP$updrs2> median(target_LSP$updrs2)
target_LSP$moca_bin= target_LSP$moca2 >  24

data4plot= target_LSP %>% group_by(updrs2_binned, moca_bin, ind) %>% summarise( power= mean(log(values)), SEM= (sd(log(values))/sqrt(n())))
data4plot= data4plot[!is.na(data4plot$updrs2_binned),]
data4plot= data4plot[!is.na(data4plot$moca_bin),]

control=cbind(data4plot[1:451,1:2],control[,-1])
control$Group= 'Control'
control$updrs2_binned= 'FALSE'
control$moca_bin= 'Control'

control2=control
control2$Group= 'Control'
control2$updrs2_binned= 'TRUE'
control2$moca_bin= 'Control'

data4plot$updrs2_binned= as.character(data4plot$updrs2_binned)
data4plot$moca_bin= as.character(data4plot$moca_bin)
data4plot$Group='PD'
data4plot=rbind(control,control2, data4plot)


ggplot(data4plot, aes(x= ind, y = power, fill= moca_bin,colour= moca_bin, ymin=power-SEM, ymax=power+SEM, linetype= updrs2_binned)) + geom_ribbon(alpha=0.5, colour= NA) + geom_line() + theme_classic2() +  xlim(1,100) +  coord_cartesian(xlim = c(1, 40), ylim= c(-2,3.5) ) + scale_color_manual(values=cbbPalette[c(1, 5,7)]) + scale_fill_manual(values=cbbPalette[c(1, 5,7)]) + facet_wrap(~updrs2_binned)

ggsave('~/Documents/PD_fingerprinting/figure/Spectrum_right_pericalcarine_MOCA_inter.pdf', device = "pdf", width=10, height=5, dpi=800)

# plot by H&Y status

data$HY_bin = data$Hoehn.and.Yahr.score >1.5
roi_index= (451*(46-1)+1):(451*(46-1)+451)

target_LSP= target[,roi_index]
database_LSP= database[,roi_index]

target_LSP= (target_LSP+database_LSP)/2

target_LSP= cbind(data, stack(target_LSP))

target_LSP$ind = plyr::mapvalues(target_LSP$ind , unique(target_LSP$ind ), seq(0,150,1/3))

target_LSP$ind= as.numeric(as.character(target_LSP$ind))

target_LSP$ind= as.numeric(as.character(target_LSP$ind))
target_LSP= target_LSP[!is.na(target_LSP$updrs2),]
target_LSP= target_LSP[!is.na(target_LSP$HY_bin),]
target_LSP$updrs2_binned=target_LSP$updrs2>median(target_LSP$updrs2)

data4plot= target_LSP %>% group_by(HY_bin, ind) %>% summarise( power= mean(log(values)), SEM= (sd(log(values))/sqrt(n())))
data4plot= data4plot[!is.na(data4plot$HY_bin),]

ggplot(data4plot, aes(x= ind, y = power, fill= HY_bin,colour= HY_bin, ymin=power-SEM, ymax=power+SEM)) + geom_ribbon(alpha=0.5, colour= NA) + geom_line() + theme_classic2() + xlim(1,100) +  coord_cartesian(xlim = c(1, 40), ylim= c(-2,3.5) )+ scale_color_manual(values=cbbPalette[c(5,7)]) + scale_fill_manual(values=cbbPalette[c(5,7)])

ggsave('~/Documents/PD_fingerprinting/figure/Spectrum_right_postcentral_HY.pdf', device = "pdf", width=5, height=5, dpi=800)



roi_index= (451*(46-1)+1):(451*(46-1)+451)

target_LSP= target[,roi_index]
database_LSP= database[,roi_index]

target_LSP= (target_LSP+database_LSP)/2

target_LSP= cbind(data, stack(target_LSP))

target_LSP$ind = plyr::mapvalues(target_LSP$ind , unique(target_LSP$ind ), seq(0,150,1/3))

target_LSP$ind= as.numeric(as.character(target_LSP$ind))


controls= target_LSP %>% group_by(Group, ind) %>% summarise( power= mean(log(values)), SEM= (sd(log(values))/sqrt(n())))

controls=controls[controls$Group=='Control',]

colnames(controls)[1]= 'HY_bin'
controls$Group = 'Controls'

data4plot$HY_bin= as.character(data4plot$HY_bin)
data4plot$Group='PD'
data4plot=rbind(controls, data4plot)

ggplot(data4plot, aes(x= ind, y = power, fill= HY_bin,colour= HY_bin, ymin=power-SEM, ymax=power+SEM)) + geom_ribbon(alpha=0.5, colour= NA) + geom_line() + theme_classic2() +xlim(1,100) +  coord_cartesian(xlim = c(1, 40), ylim= c(-2,3.5) )+ theme(legend.position = 'none')+ scale_color_manual(values=cbbPalette[c(1,5,7)]) + scale_fill_manual(values=cbbPalette[c(1,5,7)])

ggsave('~/Documents/PD_fingerprinting/figure/Spectrum_right_postcentral_HY_controls.pdf', device = "pdf", width=5, height=5, dpi=800)



roi_index= (451*(59-1)+1):(451*(59-1)+451)

target_LSP= target[,roi_index]
database_LSP= database[,roi_index]

target_LSP= (target_LSP+database_LSP)/2

target_LSP= cbind(data, stack(target_LSP))

target_LSP$ind = plyr::mapvalues(target_LSP$ind , unique(target_LSP$ind ), seq(0,150,1/3))

target_LSP$ind= as.numeric(as.character(target_LSP$ind))


data4plot= target_LSP %>% group_by(Group, ind) %>% summarise( power= mean(log(values)), SEM= (sd(log(values))/sqrt(n())))
data4plot= data4plot[!is.na(data4plot$Group),]

control= data4plot[data4plot$Group=='Control',]

ggplot(data4plot, aes(x= ind, y = power, fill= Group,colour= Group, ymin=power-SEM, ymax=power+SEM)) + geom_ribbon(alpha=0.5, colour= NA) + geom_line() + theme_classic2() + xlim(1,100) +  coord_cartesian(xlim = c(1, 40), ylim= c(-2,3.5) )

ggsave('~/Documents/PD_fingerprinting/figure/Spectrum_right_postcentral_HY_group.pdf', device = "pdf", width=10, height=5, dpi=800)

```




``` {r Plot brief participant differentiation accuracy}

# look at 30 second fingerprints
# see python scripts
cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

df=read.csv("~/Documents/PD_fingerprinting/new_analysis_Nov2022/short_recordings.csv", header = TRUE, stringsAsFactors = FALSE)
df$band= factor(df$band,levels = c("Fullband"))
df$band=plyr::mapvalues(df$band, unique(df$band), c( "broadband"))

df$Group= factor(df$Group,levels = c("CTL", "PD", 'PDvsCTL'))
df$Group=plyr::mapvalues(df$Group, unique(df$Group), c( "control", "PD", "PD vs HC"))
df$dataset_distance=df$dataset2 - df$dataset1
df$ACC= rowMeans(df[,3:4])
df$ACC=as.numeric(df$ACC)*100

data_plot=df
dodge <- position_dodge(width = 0.9)
ggplot(data=data_plot, aes(x=band, y=ACC,fill=Group, colour=Group, width=.5)) +  geom_jitter(position= position_jitterdodge(jitter.width=0.2, dodge.width=0.9), size=4, alpha =0.7 ) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.5, position = dodge, colour='#B7BBBE')  +
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7, position = dodge)  +theme_classic() + labs(y="differentiation accuracy (%)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette) + coord_cartesian(ylim = c(0, 100))

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/SHORT_fingerprinting_cohort_bands_4_cat.pdf', device = "pdf", width=8, height=8, dpi=800)



cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

df=read.csv("~/Documents/PD_fingerprinting/new_analysis_Nov2022/short_recordings.csv", header = TRUE, stringsAsFactors = FALSE)
df$band= factor(df$band,levels = c("Fullband"))
df$band=plyr::mapvalues(df$band, unique(df$band), c( "broadband"))


df_aperiodic = read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/short_recordings_aperiodic.csv', header = TRUE)
df_aperiodic$band= 'aperiodic'
df_corrspec = read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/short_recordings_corr_spec.csv', header = TRUE)
df_corrspec$band= 'corrected'
df=rbind(df_aperiodic, df_corrspec)



df$Group= factor(df$Group,levels = c("CTL", "PD", 'PDvsCTL'))
df$Group=plyr::mapvalues(df$Group, unique(df$Group), c( "control", "PD", "PD vs HC"))
df$dataset_distance=df$dataset2 - df$dataset1
df$ACC= rowMeans(df[,3:4])
df$ACC=as.numeric(df$ACC)*100

data_plot=df
dodge <- position_dodge(width = 0.9)
ggplot(data=data_plot, aes(x=band, y=ACC,fill=Group, colour=Group, width=.5)) +  geom_jitter(position= position_jitterdodge(jitter.width=0.2, dodge.width=0.9), size=4, alpha =0.7 ) +
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7, position = dodge)  +theme_classic() + labs(y="differentiation accuracy (%)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) +  scale_color_manual(values=cbbPalette) + coord_cartesian(ylim = c(0, 100)) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/SHORT_fingerprinting_aperiodic22.pdf', device = "pdf", width=8, height=8, dpi=800)


```



``` {r self-similarity of brief segments & modelling full spectra }

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

data$moca_bin= data$moca2 > 24

# # # # # # # organize 30 second data into one large matrix for plotting and modelling

df = read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023_short_recordings_NEW_self_corr.csv', header = FALSE)
temp = read.csv("~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023_complete_subj_short_recordings_NEW.csv", header = FALSE, stringsAsFactors = FALSE)

temp$dataset_distance=temp$V4 - temp$V3
colnames(temp)[1:4]= c('ACC1', 'ACC2', 'dataset1', 'dataset2')
  
self_corr= cbind(stack(df), rep(temp$dataset1[1:78], each=133), rep(temp$dataset2[1:78], each=133), rep(temp$dataset_distance[1:78], each=133), rep(data$Group,78), rep(data$updrs2,78), rep(data$moca2,78),rep(data$recording_length,78), rep(data$HLU,78), rep(data$SubjID,78), rep(data$NPall,78), rep(data$rigidity_SUM_UPDRS,78), rep(data$rest_tremor_SUM_UPDRS,78), rep(data$bradykinesia_SUM_UPDRS,78), rep(data$postural_tremor_SUM_UPDRS,78) )

colnames(self_corr)[c(3,4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)] = c('dataset1', 'dataset2', 'Group', 'updrs2', 'moca2', 'recording_length', 'HLU', 'SubjId', 'NPall', 'rigidity_SUM_UPDRS','rest_tremor_SUM_UPDRS', 'bradykinesia_SUM_UPDRS', 'postural_tremor_SUM_UPDRS' )

self_corr$dataset_distance= self_corr$dataset2 - self_corr$dataset1
self_corr$band = 'broadband'

self_corr$moca_bin= self_corr$moca2 < 24
self_corr$moca_bin[self_corr$Group =='Control']='Control'


self_corr$updrs2_bin= self_corr$updrs2 >= median(self_corr$updrs2, na.rm = TRUE)
self_corr$updrs2_bin[self_corr$Group =='Control']='Control'

data_plot=self_corr
ggplot(data=data_plot, aes(x=dataset_distance2, y=values, colour=Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) + #geom_smooth(method = "lm",aes(fill = Group), size=2) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay.pdf', device = "pdf", width=8, height=8, dpi=800)

data_plot=self_corr
data_plot$values = DescTools::FisherZ(data_plot$values)
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) + #geom_smooth(method = "lm",aes(fill = Group), size=2) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_fisherZ.pdf', device = "pdf", width=8, height=8, dpi=800)


data_plot=self_corr
data_plot$values = DescTools::FisherZ(data_plot$values)
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, fill= Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) +  stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_fisherZ_fit_poly.pdf', device = "pdf", width=8, height=8, dpi=800)


data_plot=self_corr
data_plot$values = DescTools::FisherZ(data_plot$values)
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, fill= Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) +  stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) + coord_cartesian(ylim = c(0.7, 2)) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_fisherZ_fit_poly_range.pdf', device = "pdf", width=8, height=8, dpi=800)

data4reg=self_corr
colnames(data4reg)[11]='SubjId'
data4reg$values= DescTools::FisherZ(data4reg$values)

data4reg$dataset_distance= scale(data4reg$dataset_distance)
data4reg$HLU= scale(data4reg$HLU)

lm0=lmer(values ~ 1 + (1 | SubjId), data4reg)
lm1=lmer(values ~ 1 + HLU+ dataset_distance + (1 + dataset_distance | SubjId), data4reg)
lm2=lmer(values ~ 1 + HLU+ dataset_distance + Group + (1 + dataset_distance | SubjId), data4reg)
lm3=lmer(values ~ 1 + HLU+dataset_distance +Group*dataset_distance + (1 + dataset_distance | SubjId), data4reg)

anova(lm0, lm1,lm2,lm3)
summary(lm3)
sjPlot::tab_model(lm3)

lm33=lmer(values ~ 1 + HLU+  Group*poly(dataset_distance, 2) + (1 + poly(dataset_distance, 2) | SubjId), data4reg)

sjPlot::tab_model(lm33)



```


``` {r self-similarity of brief segments with modelling aperiodic}

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

data$moca_bin= data$moca2 > 24

# # # # # # # 

df = read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023_aperiodic_short_recordings_NEW_self_corr.csv', header = FALSE)
temp = read.csv("~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023_aperiodic_complete_subj_short_recordings_NEW.csv", header = FALSE, stringsAsFactors = FALSE)

temp$dataset_distance=temp$V4 - temp$V3
colnames(temp)[1:4]= c('ACC1', 'ACC2', 'dataset1', 'dataset2')
  
self_corr= cbind(stack(df), rep(temp$dataset1[1:78], each=133), rep(temp$dataset2[1:78], each=133), rep(temp$dataset_distance[1:78], each=133), rep(data$Group,78), rep(data$updrs2,78), rep(data$moca2,78),rep(data$recording_length,78), rep(data$HLU,78), rep(data$SubjID,78), rep(data$NPall,78), rep(data$rigidity_SUM_UPDRS,78), rep(data$rest_tremor_SUM_UPDRS,78), rep(data$bradykinesia_SUM_UPDRS,78), rep(data$postural_tremor_SUM_UPDRS,78) )

colnames(self_corr)[c(3,4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)] = c('dataset1', 'dataset2', 'Group', 'updrs2', 'moca2', 'recording_length', 'HLU', 'SubjId', 'NPall', 'rigidity_SUM_UPDRS','rest_tremor_SUM_UPDRS', 'bradykinesia_SUM_UPDRS', 'postural_tremor_SUM_UPDRS' )

self_corr$dataset_distance= self_corr$dataset2 - self_corr$dataset1
self_corr$band = 'broadband'

self_corr$moca_bin= self_corr$moca2 < 24
self_corr$moca_bin[self_corr$Group =='Control']='Control'


self_corr$updrs2_bin= self_corr$updrs2 >= median(self_corr$updrs2, na.rm = TRUE)
self_corr$updrs2_bin[self_corr$Group =='Control']='Control'

data_plot=self_corr
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) + #geom_smooth(method = "lm",aes(fill = Group), size=2) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_aperiodic.pdf', device = "pdf", width=8, height=8, dpi=800)

data_plot=self_corr
data_plot$values = DescTools::FisherZ(data_plot$values)
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) + #geom_smooth(method = "lm",aes(fill = Group), size=2) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_fisherZ_aperiodic.pdf', device = "pdf", width=8, height=8, dpi=800)


 data_plot=self_corr
data_plot$values = DescTools::FisherZ(data_plot$values)
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, fill= Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) +  stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_fisherZ_aperiodic_fit_poly.pdf', device = "pdf", width=8, height=8, dpi=800)


 data_plot=self_corr
data_plot$values = DescTools::FisherZ(data_plot$values)
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, fill= Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) +  stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) + coord_cartesian(ylim = c(0.7, 2)) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_fisherZ_aperiodic_fit_poly_range.pdf', device = "pdf", width=8, height=8, dpi=800)


data4reg=self_corr
colnames(data4reg)[11]='SubjId'


data4reg$dataset_distance= scale(data4reg$dataset_distance)
data4reg$HLU= scale(data4reg$HLU)

data4reg$values= DescTools::FisherZ(data4reg$values)
lm0=lmer(values ~ 1 + (1 | SubjId), data4reg)
lm1=lmer(values ~ 1 + HLU+ dataset_distance + (1 + dataset_distance | SubjId), data4reg)
lm2=lmer(values ~ 1 + HLU+ dataset_distance + Group + (1 + dataset_distance | SubjId), data4reg)
lm3=lmer(values ~ 1 + HLU+dataset_distance +Group*dataset_distance + (1 + dataset_distance | SubjId), data4reg)

anova(lm0, lm1,lm2,lm3)
summary(lm3)
sjPlot::tab_model(lm3)

lm33=lmer(values ~ 1 + HLU+  Group*poly(dataset_distance, 2) + (1 + poly(dataset_distance, 2) | SubjId), data4reg)

sjPlot::tab_model(lm33)

anova(lm33, lm3)


```


``` {r self-similarity of brief segments with modelling  aperiodic corrected }

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

data$moca_bin= data$moca2 > 24

# # # # # # # 

df = read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023_corrspec_short_recordings_NEW_self_corr.csv', header = FALSE)
temp = read.csv("~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023_corrspec_complete_subj_short_recordings_NEW.csv", header = FALSE, stringsAsFactors = FALSE)

temp$dataset_distance=temp$V4 - temp$V3
colnames(temp)[1:4]= c('ACC1', 'ACC2', 'dataset1', 'dataset2')
  
self_corr= cbind(stack(df), rep(temp$dataset1[1:78], each=133), rep(temp$dataset2[1:78], each=133), rep(temp$dataset_distance[1:78], each=133), rep(data$Group,78), rep(data$updrs2,78), rep(data$moca2,78),rep(data$recording_length,78), rep(data$HLU,78), rep(data$SubjID,78), rep(data$NPall,78), rep(data$rigidity_SUM_UPDRS,78), rep(data$rest_tremor_SUM_UPDRS,78), rep(data$bradykinesia_SUM_UPDRS,78), rep(data$postural_tremor_SUM_UPDRS,78) )

colnames(self_corr)[c(3,4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)] = c('dataset1', 'dataset2', 'Group', 'updrs2', 'moca2', 'recording_length', 'HLU', 'SubjId', 'NPall', 'rigidity_SUM_UPDRS','rest_tremor_SUM_UPDRS', 'bradykinesia_SUM_UPDRS', 'postural_tremor_SUM_UPDRS' )

self_corr$dataset_distance= self_corr$dataset2 - self_corr$dataset1
self_corr$band = 'broadband'

self_corr$moca_bin= self_corr$moca2 < 24
self_corr$moca_bin[self_corr$Group =='Control']='Control'


self_corr$updrs2_bin= self_corr$updrs2 >= median(self_corr$updrs2, na.rm = TRUE)
self_corr$updrs2_bin[self_corr$Group =='Control']='Control'

data_plot=self_corr
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) + #geom_smooth(method = "lm",aes(fill = Group), size=2) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_corrspec.pdf', device = "pdf", width=8, height=8, dpi=800)

data_plot=self_corr
data_plot$values = DescTools::FisherZ(data_plot$values)
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) + #geom_smooth(method = "lm",aes(fill = Group), size=2) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_fisherZ_corrspec.pdf', device = "pdf", width=8, height=8, dpi=800)



data_plot=self_corr
data_plot$values = DescTools::FisherZ(data_plot$values)
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, fill= Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) +  stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_fisherZ_corrspec_fit_poly.pdf', device = "pdf", width=8, height=8, dpi=800)


data_plot=self_corr
data_plot$values = DescTools::FisherZ(data_plot$values)
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, fill= Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) +  stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) + coord_cartesian(ylim = c(0.7, 2)) 

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/11112023_SHORT_self_similairty_decay_fisherZ_corrspec_fit_poly_range.pdf', device = "pdf", width=8, height=8, dpi=800)



data4reg=self_corr
colnames(data4reg)[11]='SubjId'

data4reg$dataset_distance= scale(data4reg$dataset_distance)
data4reg$HLU= scale(data4reg$HLU)

data4reg$values= DescTools::FisherZ(data4reg$values)
lm0=lmer(values ~ 1 + (1 | SubjId), data4reg)
lm1=lmer(values ~ 1 + HLU+ dataset_distance + (1 + dataset_distance | SubjId), data4reg)
lm2=lmer(values ~ 1 + HLU+ dataset_distance + Group + (1 + dataset_distance | SubjId), data4reg)
lm3=lmer(values ~ 1 + HLU+dataset_distance +Group*dataset_distance + (1 + dataset_distance | SubjId), data4reg)

anova(lm0, lm1,lm2,lm3)
summary(lm3)
sjPlot::tab_model(lm3)




```





``` {r self-similarity brief segments aperiodic corrected narrow bands}

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

data$moca_bin= data$moca2 > 24

# # # # # # # 
# read in data from corresponding frequency band
df = read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2024_THETA_corrspec_short_recordings_NEW_self_corr.csv', header = FALSE)
temp = read.csv("~/Documents/PD_fingerprinting/new_analysis_Nov2022/2024_corrspec_THETA_complete_subj_short_recordings_NEW.csv", header = FALSE, stringsAsFactors = FALSE)

temp$dataset_distance=temp$V4 - temp$V3
colnames(temp)[1:4]= c('ACC1', 'ACC2', 'dataset1', 'dataset2')
  
self_corr= cbind(stack(df), rep(temp$dataset1[1:78], each=133), rep(temp$dataset2[1:78], each=133), rep(temp$dataset_distance[1:78], each=133), rep(data$Group,78), rep(data$updrs2,78), rep(data$moca2,78),rep(data$recording_length,78), rep(data$HLU,78), rep(data$SubjID,78), rep(data$NPall,78), rep(data$rigidity_SUM_UPDRS,78), rep(data$rest_tremor_SUM_UPDRS,78), rep(data$bradykinesia_SUM_UPDRS,78), rep(data$postural_tremor_SUM_UPDRS,78) )

colnames(self_corr)[c(3,4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)] = c('dataset1', 'dataset2', 'Group', 'updrs2', 'moca2', 'recording_length', 'HLU', 'SubjId', 'NPall', 'rigidity_SUM_UPDRS','rest_tremor_SUM_UPDRS', 'bradykinesia_SUM_UPDRS', 'postural_tremor_SUM_UPDRS' )

self_corr$dataset_distance= self_corr$dataset2 - self_corr$dataset1
self_corr$band = 'broadband'

self_corr$moca_bin= self_corr$moca2 < 24
self_corr$moca_bin[self_corr$Group =='Control']='Control'


self_corr$updrs2_bin= self_corr$updrs2 >= median(self_corr$updrs2, na.rm = TRUE)
self_corr$updrs2_bin[self_corr$Group =='Control']='Control'


data_plot=self_corr
data_plot$values = DescTools::FisherZ(data_plot$values)
ggplot(data=data_plot, aes(x=dataset_distance, y=values, colour=Group, fill= Group, width=.5)) + stat_summary(fun.data = mean_se, geom = "errorbar", size=2.5, width=0.0) +  stat_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE) + 
  stat_summary(fun.data = "mean_cl_boot", geom = "point", size= 7,)  +theme_classic() + labs(y="auto-correlation (r)", x="",title="") +  theme(text = element_text(size=40), legend.title=element_blank()) + scale_color_manual(values=cbbPalette[c(1,3)]) + scale_fill_manual(values=cbbPalette[c(1,3)]) + theme(legend.position = 'none')

ggsave('~/Documents/PD_fingerprinting/new_analysis_Nov2022/figure/2024_SHORT_self_similairty_THETA_decay_fisherZ_corrspec_fit_poly.pdf', device = "pdf", width=8, height=8, dpi=800)



```


```{r Iterate through features to differentiate other group top 10% vs bottom 10% }

# use top 10% of PD ICC features to differentiate PD and CTLS
# repeat for bottom 10%

# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

target= read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_corrected_target.csv' )

database= read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_corrected_database.csv' )

target=target[,-1]
database=database[,-1]

database=database[,-7281]
target=target[,-7281]

# now check how change in cortical thickness relates to ICC and differentiability 
#### diff in ICC between PD and CTLS
df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
df2=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_PD.csv', header = FALSE, stringsAsFactors = FALSE)
df[,2:116]=df2[,2:116]-df[,2:116]
colnames(df)[1]='region'

icc_diff=df[,-1]

count=1
fingerprint_boot_PD=matrix(, ncol = 10,nrow=200)
fingerprint_boot_control=matrix(, ncol = 10,nrow=200)

upper= c(1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1)
lower= c(0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0 )

for (k in 1:length(lower)){
  
index_feats_young= c(t(icc_diff)) > quantile(c(t(icc_diff)), lower[k]) & c(t(icc_diff)) < quantile(c(t(icc_diff)), upper[k])


ind=data$Group=='Parkinson'
psd_rest_age= target[ind,index_feats_young]
psd_task_age= database[ind,index_feats_young]

temp_boot=matrix(, ncol = 2,nrow=100)

for(i in 1:100) {
  index_random_par=sample(1:sum(ind), 50)
  
  corr_psd=cor(t(psd_rest_age[index_random_par,]),t(psd_task_age[index_random_par,])) 
  tt=apply(corr_psd, 1, which.max)
  temp_boot[i,1]=sum(seq(1:50)==tt)/50
  tt=apply(corr_psd, 2, which.max)
  temp_boot[i,2]=sum(seq(1:50)==tt)/50
  
}

fingerprint_boot_PD[,count]= as.vector(temp_boot)
write.csv(fingerprint_boot_PD, '~/Documents/PD_fingerprinting/new_analysis_features_top2bottom_fingerprinting_PD.csv')

mean(as.vector(temp_boot), na.rm = TRUE)
sd(as.vector(temp_boot), na.rm = TRUE)


ind=data$Group=='Control'
psd_rest_age= target[ind,index_feats_young]
psd_task_age= database[ind,index_feats_young]

temp_boot=matrix(, ncol = 2,nrow=100)

for(i in 1:100) {
  index_random_par=sample(1:sum(ind), 50)
  
  corr_psd=cor(t(psd_rest_age[index_random_par,]),t(psd_task_age[index_random_par,])) 
  tt=apply(corr_psd, 1, which.max)
  temp_boot[i,1]=sum(seq(1:50)==tt)/50
  tt=apply(corr_psd, 2, which.max)
  temp_boot[i,2]=sum(seq(1:50)==tt)/50
  
}

fingerprint_boot_control[,count]= as.vector(temp_boot)
write.csv(fingerprint_boot_control, '~/Documents/PD_fingerprinting/new_analysis_features_top2bottom_fingerprinting_control.csv')

mean(as.vector(temp_boot), na.rm = TRUE)
sd(as.vector(temp_boot), na.rm = TRUE)

count=count+1
}


```

```{r Plot accuracy from top 10% features from other group }

cbbPalette <- c( "#90319D","#F0792C", "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

control_adults=read.csv('~/Documents/PD_fingerprinting/new_analysis_features_top2bottom_fingerprinting_control.csv')

PD=read.csv('~/Documents/PD_fingerprinting/new_analysis_features_top2bottom_fingerprinting_PD.csv')

data4plot=rbind(data.frame(stack(control_adults[-1]), group= 'control'),
data.frame(stack(PD[-1]), group= 'PD'))

data4plot=data4plot %>% group_by(group, ind) %>% summarise(m_acc= mean(values), CI= sd(values))

data4plot$ind= plyr::mapvalues(data4plot$ind,
                               c('V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10'),
                               1-c(1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1))

data4plot$group= factor(data4plot$group, levels= c('control', 'adult', 'PD'))

ggplot(data4plot, aes(x=ind, y=m_acc, group=group, color = group, fill=group)) + geom_point(size=4) +
  geom_line(aes(x=ind, y=m_acc, color=group), linetype='dotted') +
  geom_errorbar(aes(ymin=m_acc-CI,ymax=m_acc+CI,fill=group),width=0.0, size=1) +ggpubr::theme_classic2() + scale_colour_manual(values=cbbPalette) + scale_fill_manual(values=cbbPalette) + labs(y="Accuracy (%)", x="top % ICC features",title="") + theme(text = element_text(size=40), legend.title=element_blank()) 

ggsave('~/Documents/PD_fingerprinting/figure/jfingerpritnt_individuals_from_other_group_top2bottom.pdf', device = "pdf", width=15, height=5, dpi=800)


```



```{r Plot brainmaps of Intraclass correlations}


df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right' 
df$hemi[seq(1,67,2)] ='left'

# Parkinsons
someData= tibble(df$region, rowMeans(df[,85:116]), df$hemi)
colnames(someData)[2]='ICC'
colnames(someData)[1]='region'
colnames(someData)[3]='hemi'
someData$ICC[someData$ICC<0.4]=0.4
someData$ICC[someData$ICC>0.9]=0.9
someData$band= 'gamma'
someData2= tibble(df$region, rowMeans(df[,34:84]), df$hemi)
colnames(someData2)[2]='ICC'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'
someData2$ICC[someData2$ICC<0.4]=0.4
someData2$ICC[someData2$ICC>0.9]=0.9
someData2$band= 'beta'
someData=rbind(someData,someData2)
someData2= tibble(df$region, rowMeans(df[,19:33]), df$hemi)
colnames(someData2)[2]='ICC'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'
someData2$ICC[someData2$ICC<0.4]=0.4
someData2$ICC[someData2$ICC>0.9]=0.9
someData2$band= 'alpha'
someData=rbind(someData,someData2)
someData2= tibble(df$region, rowMeans(df[,7:18]), df$hemi)
colnames(someData2)[2]='ICC'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'
someData2$ICC[someData2$ICC<0.4]=0.4
someData2$ICC[someData2$ICC>0.9]=0.9
someData2$band= 'theta'


someData$band= ordered(someData$band, levels= c("theta", "alpha", "beta", "gamma"))
someData= someData[!is.na(someData$band),]
ggplot(someData) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = ICC)) + viridis::scale_fill_viridis(option = 'magma',limits=c(0.4, 1 ))+ theme_void() + facet_wrap(~band, nrow = 1)

ggsave('~/Documents/PD_fingerprinting/ICC_output/ICC_corrected_spectra_controls.pdf', device = "pdf")


someDatam=someData %>% group_by(region, hemi) %>% summarise(mICC=mean(ICC))
someDatam=merge(dk, someDatam)
ggplot(someDatam) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = mICC)) + viridis::scale_fill_viridis(option = 'magma',limits=c(0.4, 1 ))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/ICC_corrected_spectra_controls_broadband.pdf', device = "pdf")


df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_PD.csv', header = FALSE, stringsAsFactors = FALSE)
colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right' 
df$hemi[seq(1,67,2)] ='left'

# Parkinsons
someData= tibble(df$region, rowMeans(df[,85:116]), df$hemi)
colnames(someData)[2]='ICC'
colnames(someData)[1]='region'
colnames(someData)[3]='hemi'
someData$ICC[someData$ICC<0.4]=0.4
someData$ICC[someData$ICC>0.9]=0.9
someData$band= 'gamma'
someData2= tibble(df$region, rowMeans(df[,34:84]), df$hemi)
colnames(someData2)[2]='ICC'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'
someData2$ICC[someData2$ICC<0.4]=0.4
someData2$ICC[someData2$ICC>0.9]=0.9
someData2$band= 'beta'
someData=rbind(someData,someData2)
someData2= tibble(df$region, rowMeans(df[,19:33]), df$hemi)
colnames(someData2)[2]='ICC'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'
someData2$ICC[someData2$ICC<0.4]=0.4
someData2$ICC[someData2$ICC>0.9]=0.9
someData2$band= 'alpha'
someData=rbind(someData,someData2)
someData2= tibble(df$region, rowMeans(df[,7:18]), df$hemi)
colnames(someData2)[2]='ICC'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'
someData2$ICC[someData2$ICC<0.4]=0.4
someData2$ICC[someData2$ICC>0.9]=0.9
someData2$band= 'theta'


someData$band= ordered(someData$band, levels= c("theta", "alpha", "beta", "gamma"))
someData= someData[!is.na(someData$band),]
ggplot(someData) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = ICC)) + viridis::scale_fill_viridis(option = 'magma',limits=c(0.4, 1 ))+ theme_void() + facet_wrap(~band, nrow = 1)

ggsave('~/Documents/PD_fingerprinting/ICC_output/ICC_corrected_spectra_PD.pdf', device = "pdf")

someDatam=someData %>% group_by(region, hemi) %>% summarise(mICC=mean(ICC))
someDatam=merge(dk, someDatam)
ggplot(someDatam) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = mICC)) + viridis::scale_fill_viridis(option = 'magma',limits=c(0.4, 1 ))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/ICC_corrected_spectra_PD_broadband.pdf', device = "pdf")


#### diff in ICC between PD and CTLS
df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
df2=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_PD.csv', header = FALSE, stringsAsFactors = FALSE)
df[,2:116]=df2[,2:116]-df[,2:116]

colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'

# Parkinsons
someData= tibble(df$region, rowMeans(df[,85:116]), df$hemi)
colnames(someData)[2]='ICC'
colnames(someData)[1]='region'
colnames(someData)[3]='hemi'
someData$band= 'gamma'
someData2= tibble(df$region, rowMeans(df[,34:84]), df$hemi)
colnames(someData2)[2]='ICC'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'
someData2$band= 'beta'
someData=rbind(someData,someData2)
someData2= tibble(df$region, rowMeans(df[,19:33]), df$hemi)
colnames(someData2)[2]='ICC'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'
someData2$band= 'alpha'
someData=rbind(someData,someData2)
someData2= tibble(df$region, rowMeans(df[,7:18]), df$hemi)
colnames(someData2)[2]='ICC'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'
someData2$band= 'theta'
someData=rbind(someData,someData2)


someData= someData[!is.na(someData$region),]
ggplot(someData) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = ICC)) +
  #viridis::scale_fill_viridis(option = 'magma',limits=c(-0.5, 0.5 ))+
    scale_fill_gradient2(low = "#67309A", mid = "#FCF7F4", high = "#EC7A48", midpoint = 0.0, limits=c(-0.5, 0.5 )) +
  theme_void() + facet_wrap(~band)

ggsave('~/Documents/PD_fingerprinting/ICC_output/ICC_corrected_spectra_diff.pdf', device = "pdf")



#### diff in ICC between PD and CTLS
df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
df2=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_PD.csv', header = FALSE, stringsAsFactors = FALSE)
df2[,2:116]=df2[,2:116]-df[,2:116]

colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'

# Define X and Y data
X=data.frame(theta= rowMeans(df2[,7:18]),alpha= rowMeans(df2[,19:33]),beta= rowMeans(df2[,34:84]), gamma= rowMeans(df2[,84:116]))

x2=rowMeans(X)


# fullband
someData3= tidyr::tibble(df$region, x2, df$hemi)
colnames(someData3)= c('region', 'ICC', 'hemi')

someData3$ICC[someData3$ICC >0.5] =0.5
someData3$ICC[someData3$ICC < -0.5] = -0.5

someData3= someData3[!is.na(someData3$region),]
ggplot(someData3) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = ICC)) +
  #viridis::scale_fill_viridis(option = 'magma',limits=c(-0.5, 0.5 ))+
    scale_fill_gradient2(low = "#67309A", mid = "#FCF7F4", high = "#EC7A48", midpoint = 0.0, limits=c(-0.5, 0.5 )) +
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/ICC_corrected_spectra_AVG_PD_minus_CTL_new.pdf', device = "pdf")




# fullband
someData3= tidyr::tibble(df$region, x2, df$hemi)
colnames(someData3)= c('region', 'ICC', 'hemi')

someData3$ICC[someData3$ICC >0.2] =0.2
someData3$ICC[someData3$ICC < -0.2] = -0.2

someData3= someData3[!is.na(someData3$region),]
ggplot(someData3) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = ICC)) +
  #viridis::scale_fill_viridis(option = 'magma',limits=c(-0.5, 0.5 ))+
    scale_fill_gradient2(low = "#67309A", mid = "#FCF7F4", high = "#EC7A48", midpoint = 0.0, limits=c(-0.2, 0.2 )) +
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/ICC_corrected_spectra_AVG_PD_minus_CTL_new22.pdf', device = "pdf")


someData33=someData3
someData33$ICC[someData33$ICC >0.2] =0.2
someData33$ICC[someData33$ICC < 0] = 0

someData33= someData33[!is.na(someData33$region),]
ggplot(someData33) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = ICC)) +
  #viridis::scale_fill_viridis(option = 'magma',limits=c(-0.5, 0.5 ))+
    scale_fill_gradient2(low = "#67309A", mid = "#FCF7F4", high = "#EC7A48", midpoint = 0.0, limits=c(-0.2, 0.2 )) +
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/ICC_corrected_spectra_AVG_PD_minus_CTL_new22_pos.pdf', device = "pdf")


someData33=someData3
someData33$ICC[someData33$ICC < -0.2] = -0.2
someData33$ICC[someData33$ICC > 0] = 0

someData33= someData33[!is.na(someData33$region),]
ggplot(someData33) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = ICC)) +
  #viridis::scale_fill_viridis(option = 'magma',limits=c(-0.5, 0.5 ))+
    scale_fill_gradient2(low = "#67309A", mid = "#FCF7F4", high = "#EC7A48", midpoint = 0.0, limits=c(-0.2, 0.2 )) +
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/ICC_corrected_spectra_AVG_PD_minus_CTL_new22_neg.pdf', device = "pdf")


```


```{r ICC and cortical thickness}

# Are any of the effects we observe due to cortical thickness?
thicc=read.csv('~/Documents/PD_fingerprinting/Alex_cortical/thiccness_data.csv', stringsAsFactors = FALSE, na.strings = 0, header = FALSE)
thicc_ids= read.csv('~/Documents/PD_fingerprinting/Alex_cortical/thiccness_ids.csv', stringsAsFactors = FALSE, na.strings = 0, header = FALSE)

index= data$SubjID %in% thicc_ids$V1
demo=data[index,]

thicc=thicc[,thicc_ids$V1 %in% data$SubjID]
thicc_ids=thicc_ids[thicc_ids$V1 %in% data$SubjID,]
demo=demo[match(thicc_ids, demo$SubjID),]


thicc_zcore= (thicc - rowMeans(thicc[,demo$Group=='Control']))/apply(thicc[,demo$Group=='Control'],1, sd, na.rm = TRUE)

dka_thicc= rowMeans(thicc_zcore[,demo$Group=='Parkinson'])


df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/Nov_2022_ICC_PD_cohort.csv', header = FALSE, stringsAsFactors = FALSE)
df=df[,1:2]
colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right' 
df$hemi[seq(1,67,2)] ='left'
df$V2=dka_thicc

someData2= df
colnames(someData2)[2]='Cortical thickness'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = `Cortical thickness`)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'magma')+
  #scale_fill_gradient2(low="white", mid="#EC352F", high="#6C1917", 
  #                     midpoint=0.6,   
  #                     limits=c(0.4, 0.9 ))+
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/cortical_thiccness_PD_zscore_change.pdf', device = "pdf")


dka_thicc= rowMeans(thicc[,demo$Group=='Control'])

df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/Nov_2022_ICC_PD_cohort.csv', header = FALSE, stringsAsFactors = FALSE)
df=df[,1:2]
colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right' 
df$hemi[seq(1,67,2)] ='left'
df$V2=dka_thicc


someData2= df
colnames(someData2)[2]='Cortical thickness'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = `Cortical thickness`)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'magma')+
  #scale_fill_gradient2(low="white", mid="#EC352F", high="#6C1917", 
  #                     midpoint=0.6,   
  #                     limits=c(0.4, 0.9 ))+
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/cortical_thiccness_control_avg.pdf', device = "pdf")


dka_thicc= rowMeans(thicc[,demo$Group=='Parkinson'])

df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/Nov_2022_ICC_PD_cohort.csv', header = FALSE, stringsAsFactors = FALSE)
df=df[,1:2]
colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right' 
df$hemi[seq(1,67,2)] ='left'
df$V2=dka_thicc


someData2= df
colnames(someData2)[2]='Cortical thickness'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = `Cortical thickness`)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'magma')+
  #scale_fill_gradient2(low="white", mid="#EC352F", high="#6C1917", 
  #                     midpoint=0.6,   
  #                     limits=c(0.4, 0.9 ))+
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/cortical_thiccness_PD_avg.pdf', device = "pdf")


# now check how change in cortical thickness relates to ICC and differentiability 
#### diff in ICC between PD and CTLS
df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
df2=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_PD.csv', header = FALSE, stringsAsFactors = FALSE)
df[,2:116]=df2[,2:116]-df[,2:116]
colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'

df2=df[,-1]
# Define X and Y data
X=data.frame(theta= rowMeans(df2[,7:18]),alpha= rowMeans(df2[,19:33]),beta= rowMeans(df2[,34:84]), gamma= rowMeans(df2[,84:115]))

x2=rowMeans(X)

someData= tidyr::tibble(df$region, x2, df$hemi)
colnames(someData)[2]='ICC'
colnames(someData)[1]='region'
colnames(someData)[3]='hemi'


ggplot(someData) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = `ICC`)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'magma')+
  #scale_fill_gradient2(low="white", mid="#EC352F", high="#6C1917", 
  #                     midpoint=0.6,   
  #                     limits=c(0.4, 0.9 ))+
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/corrected_spectra_ICC_cortical_2023.pdf', device = "pdf")


dka_thicc= rowMeans(thicc_zcore[,demo$Group=='Parkinson'])
dka_thicc_no_z= rowMeans(thicc[,demo$Group=='Parkinson'])
dka_thicc_CTL= rowMeans(thicc[,demo$Group=='Control'])

cor.test(x2, dka_thicc)
cor.test(x2, dka_thicc_no_z)
cor.test(x2, dka_thicc_CTL)


# spatial permutation test Hungarian method
permuted_index= read.csv('~/Documents/CAMCAN_outputs/neuromaps/permuted_indexes_of_dk_atlas.csv')
permuted_index= permuted_index[,-1]
permuted_index=permuted_index+1

orig=cor.test(dka_thicc, x2)
permuted_corr=c()
for (i in 1:1000){
  
  cor_temp=cor.test(dka_thicc, x2[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate < permuted_corr)/1000
# permuted p value for gradient = 0.357 !


# scatter plot
someData_scatter= tidyr::tibble(df$region, x2, dka_thicc)
colnames(someData_scatter)[2]='ICC'
colnames(someData_scatter)[1]='region'
colnames(someData_scatter)[3]='Cortical thickness'

lm3=lm(`Cortical thickness` ~ ICC +1, someData_scatter)
summary(lm3)
sjPlot::tab_model(lm3)

ggplot(someData_scatter, aes(x=ICC , y = `Cortical thickness`, fill=cbbPalette[6])) + 
  geom_jitter(colour = cbbPalette[6]) + 
  stat_smooth(method = "lm", colour = 'black',fullrange = T) +
  labs(title = paste("Adj R2 = ", signif(summary(lm3)$adj.r.squared, 5),
                     "Intercept =", signif(lm3$coef[[1]],5 ),
                     " Slope =", signif(lm3$coef[[2]], 5),
                     " P =", signif(summary(lm3)$coef[2,4], 5) )) + scale_fill_manual(values=cbbPalette[6])  +
  theme_classic2() +   xlab("ICC") + ylab("Cortical thickness")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"), legend.position = "none") 


ggsave('~/Documents/PD_fingerprinting/figure/2023_Regression_cortical_thiccness_vs_ICC_aperiodic_corr.pdf', device = "pdf", width=5, height=5, dpi=800)


index= thicc_ids %in% data$SubjID 
PD_thicc= colMeans(thicc_zcore[,index])
demo$thiccness=PD_thicc

demo_regress= demo[demo$Group=="Parkinson",]

lm3=lm(thiccness ~ identifiability_aperiodiccorrect +1, demo_regress)
summary(lm3)
sjPlot::tab_model(lm3)

ggplot(demo_regress, aes(x=identifiability , y = thiccness, fill=cbbPalette[6])) + 
  geom_jitter(colour = cbbPalette[6]) + 
  stat_smooth(method = "lm", colour = 'black',fullrange = T) +
  labs(title = paste("Adj R2 = ", signif(summary(lm3)$adj.r.squared, 5),
                     "Intercept =", signif(lm3$coef[[1]],5 ),
                     " Slope =", signif(lm3$coef[[2]], 5),
                     " P =", signif(summary(lm3)$coef[2,4], 5) )) + scale_fill_manual(values=cbbPalette[6])  +
  theme_classic2() +   xlab("differentiability") + ylab("Cortical thickness")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"), legend.position = "none") 
ggsave('~/Documents/PD_fingerprinting/figure/2023_Regression_cortical_thiccness_vs_self_id_aperiodic_corr.pdf', device = "pdf", width=5, height=5, dpi=800)


```


```{r SVM to predict HY }

# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

target= read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_corrected_target.csv' )

database= read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_corrected_database.csv' )

target=target[,-1]
database=database[,-1]

predictions= c()

for (j in 1:68){

roi_index= (115*(j-1)+1):(115*(j-1)+115)

target_LSP= target[,roi_index]
database_LSP= database[,roi_index]
target_LSP= (target_LSP+database_LSP)/2

# We used various cross validation strategies
# 80-20 (10 to train 3 to test)
# 70-30 (9 to train and 4 to test)
# 90-10 (12 to train and 1 to test)
target_LSP=target_LSP[!is.na(data$Hoehn.and.Yahr.score),]
data2=data[!is.na(data$Hoehn.and.Yahr.score),]
data2$HoehnYarr_bin= data2$Hoehn.and.Yahr.score >1.5
data2$HoehnYarr_bin = as.factor(data2$HoehnYarr_bin)
data_HYpos= target_LSP[data2$Hoehn.and.Yahr.score >1.5,]
data_HYneg= target_LSP[data2$Hoehn.and.Yahr.score <=1.5,]
prediction=c()

  for (i in 1:1000){
      # for different corss validation schemes change the numbers of par in   each group
      ids_pos=sample(nrow(data_HYpos),13)
      ids_neg= sample(nrow(data_HYneg),13)

      datatrain= rbind(data_HYpos[ids_pos[1:9],], data_HYneg[ids_neg[1:9],])
      datatrain$HoehnYarr_bin= c(rep(1 ,9), rep(0,9))
      datatrain$HoehnYarr_bin= as.factor(datatrain$HoehnYarr_bin)
      datatest= rbind(data_HYpos[ids_pos[10:13],], data_HYneg[ids_neg[10:13],])
      datatest$HoehnYarr_bin= c(rep(1,4), rep(0,4))
      datatest$HoehnYarr_bin= as.factor(datatest$HoehnYarr_bin)

      svm_model=e1071::svm(HoehnYarr_bin ~., data= datatrain, kernel = "linear", cost = 1)

      pred <- predict(svm_model,datatest)
      prediction[i]=sum(pred==datatest$HoehnYarr_bin)/8
  }

predictions= cbind(predictions,prediction)
print(j)
}

predictions= as.data.frame(predictions)

write.csv(predictions, '~/Documents/PD_fingerprinting/Results_from_SVM_class_of_HY_aperiodic_corrected_70_30_33.csv')




SVM=read.csv( '~/Documents/PD_fingerprinting/Results_from_SVM_class_of_HY_aperiodic_corrected_80_20.csv')
SVM=SVM[,-1]

df=read.csv('~/Documents/Alex_fingerprinting/PSD_ICC_orig_PD_new_PKD2.csv', header = FALSE, stringsAsFactors = FALSE)
colnames(df)[1]='region'
df=df[,1:2]
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'
df$ACC=colMeans(SVM)


someData2= df
colnames(someData2)[2]='Fingerprinting accuracy'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = `ACC`)) +
   scale_fill_gradient2(low = "#ECECEC", mid = "#ECECEC", high = "#E25987", midpoint = 0.50) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  #viridis::scale_fill_viridis(option = 'magma')+
  #scale_fill_gradient2(low="white", mid="#EC352F", high="#6C1917", 
  #                     midpoint=0.6,   
  #                     limits=c(0.4, 0.9 ))+
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/2023_decode_HY_ROI_aperiodic_corrected_80_20_22.pdf', device = "pdf")



SVM=read.csv( '~/Documents/PD_fingerprinting/Results_from_SVM_class_of_HY_aperiodic_corrected_80_20.csv')
SVM=SVM[,-1]


#### diff in ICC between PD and CTLS
df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
df2=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_PD.csv', header = FALSE, stringsAsFactors = FALSE)
df2[,2:116]=df2[,2:116]-df[,2:116]

colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'

# Define X and Y data
X=data.frame(theta= rowMeans(df2[,7:18]),alpha= rowMeans(df2[,19:33]),beta= rowMeans(df2[,34:84]), gamma= rowMeans(df2[,84:116]))

df$ICC=rowMeans(X)

someData2= df
colnames(someData2)[1]='region'

cor.test(colMeans(SVM), df$ICC )



permuted_index= read.csv('~/Documents/CAMCAN_outputs/neuromaps/permuted_indexes_of_dk_atlas.csv')
permuted_index= permuted_index[,-1]
permuted_index=permuted_index+1

#gradient offset
orig=cor.test(rowMeans(X), colMeans(SVM))
permuted_corr=c()
for (i in 1001:2000){
  
  cor_temp=cor.test(rowMeans(X), colMeans(SVM)[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate < permuted_corr)/1000
# permuted p value for gradient = 0.00 !


data4reg=data.frame(SVM= colMeans(SVM), ICC=rowMeans(X))
#data4reg= as.data.frame(scale(data4reg))
lm3=lm(SVM ~ ICC, data4reg)
summary(lm3)

ggplot(data4reg, aes(x=SVM , y = ICC, fill=cbbPalette[3])) + 
  geom_jitter(colour = cbbPalette[6]) + 
  stat_smooth(method = "lm", colour = 'black',fullrange = T, fill=cbbPalette[3]) +
  labs(title = paste("Adj R2 = ", signif(summary(lm3)$adj.r.squared, 5),
                     "Intercept =", signif(lm3$coef[[1]],5 ),
                     " Slope =", signif(lm3$coef[[2]], 5),
                     " P =", signif(summary(lm3)$coef[2,4], 5) )) + scale_fill_manual(values=cbbPalette[3])  + theme_classic2() +   xlab("decoding accuracy (%)") + ylab("ICC")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"), legend.position = "none") 

ggsave('~/Documents/PD_fingerprinting/figure/2023_Regression_SVM_ICC_aperiodic_corrected_data_70_30_33.pdf', device = "pdf", width=5, height=5, dpi=800)



```



```{r SVM cross validation plots}

SVM=read.csv( '~/Documents/PD_fingerprinting/Results_from_SVM_class_of_HY_aperiodic_corrected_90_10.csv')
SVM=SVM[,-1]

df=read.csv('~/Documents/Alex_fingerprinting/PSD_ICC_orig_PD_new_PKD2.csv', header = FALSE, stringsAsFactors = FALSE)
colnames(df)[1]='region'
df=df[,1:2]
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'
df$ACC=colMeans(SVM)


someData2= df
colnames(someData2)[2]='Fingerprinting accuracy'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = `ACC`)) +
   scale_fill_gradient2(low = "#ECECEC", mid = "#ECECEC", high = "#E25987", midpoint = 0.50) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  #viridis::scale_fill_viridis(option = 'magma')+
  #scale_fill_gradient2(low="white", mid="#EC352F", high="#6C1917", 
  #                     midpoint=0.6,   
  #                     limits=c(0.4, 0.9 ))+
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/2023_decode_HY_ROI_aperiodic_corrected_90_10.pdf', device = "pdf")



SVM=read.csv( '~/Documents/PD_fingerprinting/Results_from_SVM_class_of_HY_aperiodic_corrected_70_30.csv')
SVM=SVM[,-1]

df=read.csv('~/Documents/Alex_fingerprinting/PSD_ICC_orig_PD_new_PKD2.csv', header = FALSE, stringsAsFactors = FALSE)
colnames(df)[1]='region'
df=df[,1:2]
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'
df$ACC=colMeans(SVM)


someData2= df
colnames(someData2)[2]='Fingerprinting accuracy'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = `ACC`)) +
   scale_fill_gradient2(low = "#ECECEC", mid = "#ECECEC", high = "#E25987", midpoint = 0.50, limits=c(0.5, 0.9 )) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  #viridis::scale_fill_viridis(option = 'magma')+
  #scale_fill_gradient2(low="white", mid="#EC352F", high="#6C1917", 
  #                     midpoint=0.6,   
  #                     limits=c(0.4, 0.9 ))+
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/ICC_output/2023_decode_HY_ROI_aperiodic_corrected_70_30.pdf', device = "pdf")


SVM=read.csv( '~/Documents/PD_fingerprinting/Results_from_SVM_class_of_HY_aperiodic_corrected_70_30_22.csv')
SVM=SVM[,-1]

#### diff in ICC between PD and CTLS
df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
df2=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_PD.csv', header = FALSE, stringsAsFactors = FALSE)
df2[,2:116]=df2[,2:116]-df[,2:116]

colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'

# Define X and Y data
X=data.frame(theta= rowMeans(df2[,7:18]),alpha= rowMeans(df2[,19:33]),beta= rowMeans(df2[,34:84]), gamma= rowMeans(df2[,84:116]))

df$ICC=rowMeans(X)

someData2= df
colnames(someData2)[1]='region'

cor.test(colMeans(SVM), df$ICC )


permuted_index= read.csv('~/Documents/CAMCAN_outputs/neuromaps/permuted_indexes_of_dk_atlas.csv')
permuted_index= permuted_index[,-1]
permuted_index=permuted_index+1

#gradient offset
orig=cor.test(df$ICC, colMeans(SVM))
permuted_corr=c()
for (i in 3001:4000){
  
  cor_temp=cor.test(rowMeans(X), colMeans(SVM)[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate < permuted_corr)/1000
# permuted p value for gradient = 0.001 !



SVM=read.csv( '~/Documents/PD_fingerprinting/Results_from_SVM_class_of_HY_aperiodic_corrected_90_10.csv')
SVM=SVM[,-1]


cor.test(colMeans(SVM), df$ICC )

# correction for spatial autocorrelation Hungarian method
permuted_index= read.csv('~/Documents/CAMCAN_outputs/neuromaps/permuted_indexes_of_dk_atlas.csv')
permuted_index= permuted_index[,-1]
permuted_index=permuted_index+1

orig=cor.test(df$ICC, colMeans(SVM))
permuted_corr=c()
for (i in 4001:5000){
  
  cor_temp=cor.test(rowMeans(X), colMeans(SVM)[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate < permuted_corr)/1000
# permuted p value for gradient = 0.012 !

```




``` {r neuromaps functional gradient & sptial-permutations }

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

#### diff in ICC between PD and CTLS
df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
df2=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_PD.csv', header = FALSE, stringsAsFactors = FALSE)
df2[,2:116]=df2[,2:116]-df[,2:116]

colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'

# Define X and Y data
X=data.frame(theta= rowMeans(df2[,7:18]),alpha= rowMeans(df2[,19:33]),beta= rowMeans(df2[,34:84]), gamma= rowMeans(df2[,84:116]))

x2=rowMeans(X)

# fullband
someData3= data.frame(df$region, x2, df$hemi)
colnames(someData3)= c('region', 'ICC', 'hemi')

### func grad
neuromaps= read.csv('~/Documents/PD_fingerprinting/neuromaps/receptor_data_scale033_full.csv')
cor.test(someData3$ICC, neuromaps$func_grad_01)


data4plot= data.frame(fullband= someData3$ICC, functiona_grad= neuromaps$func_grad_01)

lm3=lm(`functiona_grad` ~ fullband, data4plot)
summary(lm3)

ggplot(data4plot, aes(x=functiona_grad , y = fullband, fill=cbbPalette[6])) + 
  geom_jitter(colour = cbbPalette[6]) + 
  stat_smooth(method = "lm", colour = 'black',fullrange = T, fill=cbbPalette[6]) +
  labs(title = paste("Adj R2 = ", signif(summary(lm3)$adj.r.squared, 5),
                     "Intercept =", signif(lm3$coef[[1]],5 ),
                     " Slope =", signif(lm3$coef[[2]], 5),
                     " P =", signif(summary(lm3)$coef[2,4], 5) )) + scale_fill_manual(values=cbbPalette[4])  + theme_classic2() +   xlab("fullband PC") + ylab("functional gradient")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"), legend.position = "none") 

ggsave('~/Documents/PD_fingerprinting/figure/2023_corrected_spectra_features_relationship_2_func_grad.pdf', device = "pdf", width=5, height=5, dpi=800)



permuted_index= read.csv('~/Documents/CAMCAN_outputs/neuromaps/permuted_indexes_of_dk_atlas.csv')
permuted_index= permuted_index[,-1]
permuted_index=permuted_index+1


#gradient offset
orig=cor.test(someData3$ICC, neuromaps$func_grad_01)
permuted_corr=c()
for (i in 1:1000){
  
  cor_temp=cor.test(someData3$ICC, neuromaps$func_grad_01[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000
# permuted p value for gradient = 0.0 !


# Define X and Y data
X=data.frame(broadband= x2)
Y = neuromaps[,c(7:25)]

corr_mat=corrplot::cor.mtest(cbind(X,Y))
r_matrix=cor(cbind(X,Y))
r_matrix=r_matrix[2:20, 1]
p_val=corr_mat$p
p_val=p_val[2:20,1]
p_corrected=matrix(p.adjust(p_val, 'fdr'), nrow = 1)
p_corrected_bin=p_corrected <0.05
colnames(p_corrected_bin)= colnames(neuromaps[,c(7:25)])
colnames(p_corrected)= colnames(neuromaps[,c(7:25)])

bf_map=r_matrix

for (j in 1:19){
  bf = BayesFactor::correlationBF(y = Y[,j], x = X[,1])
  bf_map[j]=exp(as.numeric(bf@bayesFactor[1]))
}


p_longData<-reshape2::melt(bf_map)
p_longData$r_vals= round(r_matrix, 2)
p_longData$value[p_longData$value>100]=100
p_longData$Var1= factor(colnames(neuromaps[,c(7:25)]),levels = c('D1',	'D2',	'DAT',	'X5HT1a',	'X5HT1b',	'X5HT2a',	'X5HT4',	'X5HT6',	'X5HTT',	'A4B2',	'M1',	'VAChT',	'GABAa',	'NMDA',	'mGluR5',	'NET',	'H3',	'CB1',	'MOR'))

ggplot(p_longData, aes(x = Var1, y = 1, fill=value)) + 
  geom_tile(color = "gray") +  
  scale_fill_gradient2(low = "#f5ec6c", mid = "white", high = "#F0792C", midpoint = 1.0, limits= c(0,100)) +
  labs(x=" ", y="", title="") + geom_text(aes(label=r_vals), size = 7.5) +
  theme_void() + theme(axis.text.x=element_text(size=15, angle=0, vjust=0.3),
                       axis.text.y=element_text(size=15),
                       plot.title=element_text(size=15))

ggsave('~/Documents/PD_fingerprinting/figure/2023_corrected_spectra_NEUROMAPS_bayesfactor.pdf', device = "pdf", width=20, height=2, dpi=800)




#gradient offset
orig=cor.test(x2, neuromaps$X5HT4)
permuted_corr=c()
for (i in 5001:6000){
  
  cor_temp=cor.test(x2, neuromaps$X5HT4[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.007

#gradient offset
orig=cor.test(x2, neuromaps$CB1)
permuted_corr=c()
for (i in 6001:7000){
  
  cor_temp=cor.test(x2, neuromaps$CB1[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

# add one and divide by perm +1 to avoid zeros in the p values
sum(orig$estimate > permuted_corr) +1 /1001 #0.00

#gradient offset
orig=cor.test(x2, neuromaps$NET)
permuted_corr=c()
for (i in 7001:8000){
  
  cor_temp=cor.test(x2, neuromaps$CB1[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate < permuted_corr)/1000 #0.00



#gradient offset
orig=cor.test(x2, neuromaps$MOR)
permuted_corr=c()
for (i in 8001:9000){
  
  cor_temp=cor.test(x2, neuromaps$CB1[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.006

#gradient offset
orig=cor.test(x2, neuromaps$X5HT2a)
permuted_corr=c()
for (i in 8001:9000){
  
  cor_temp=cor.test(x2, neuromaps$CB1[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.00


Y = neuromaps[,7:30]
Y2= scale(Y)
Y2= as.data.frame(Y2)

df=read.csv('~/Documents/Alex_fingerprinting/PSD_ICC_orig_PD_new_PKD2.csv', header = FALSE, stringsAsFactors = FALSE)
colnames(df)[1]='region'
df_plot=df[,1:2]
df_plot$hemi =''
df_plot$hemi[seq(2,68,2)] ='right'
df_plot$hemi[seq(1,67,2)] ='left'
df_plot$receptor=rowMeans(Y2[, c(3,4)])

someData2= df_plot
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

someData2$receptor[someData2$receptor>2]=2
someData2$receptor[someData2$receptor< -2]= -2

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = receptor)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'rocket', limits = c(-2, 2))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/figure/2023_corrected_NEUROMAPS_serotonin_AVG_receptor_map.pdf', device = "pdf")

df_plot$receptor=Y2$CB1

someData2= df_plot
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

someData2$receptor[someData2$receptor>2]=2
someData2$receptor[someData2$receptor< -2]= -2

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = receptor)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'rocket', limits = c(-2, 2))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/figure/2023_DEC_NEUROMAPS_CB1_receptor_map.pdf', device = "pdf")



df_plot$receptor=Y2$NET

someData2= df_plot
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

someData2$receptor[someData2$receptor>2]=2
someData2$receptor[someData2$receptor< -2]= -2

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = receptor)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'rocket', limits = c(-2, 2))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/figure/2023_DEC_NEUROMAPS_NET_receptor_map.pdf', device = "pdf")



df_plot$receptor=Y2$MOR

someData2= df_plot
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

someData2$receptor[someData2$receptor>2]=2
someData2$receptor[someData2$receptor< -2]= -2

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = receptor)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'rocket', limits = c(-2, 2))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/figure/2023_DEC_NEUROMAPS_MOR_receptor_map.pdf', device = "pdf")




df_plot$receptor=Y2$X5HT2a

someData2= df_plot
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

someData2$receptor[someData2$receptor>2]=2
someData2$receptor[someData2$receptor< -2]= -2

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = receptor)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'rocket', limits = c(-2, 2))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/figure/2023_DEC_NEUROMAPS_X5HT2a_receptor_map.pdf', device = "pdf")



df_plot$receptor=Y2$X5HT4

someData2= df_plot
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

someData2$receptor[someData2$receptor>2]=2
someData2$receptor[someData2$receptor< -2]= -2

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = receptor)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'rocket', limits = c(-2, 2))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/figure/2023_DEC_NEUROMAPS_X5HT4_receptor_map.pdf', device = "pdf")


```



```{r Reproduce analysis with camcan}
# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

data %>% group_by(Group) %>% summarise(m_age= mean(Age, na.rm=TRUE), sd_age= sd(Age, na.rm=TRUE))
table(data$Group, data$Sex)
table(data$Group, data$Handedness)

target= read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_corrected_target.csv' )

database= read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_corrected_database.csv' )

target=target[,-1]
database=database[,-1]


z_target= t(scale(t(target[data$Group== "Parkinson",])))
z_database= t(scale(t(database[data$Group== "Parkinson",])))
icc = c()


n = 79
k = 2
df_b = n-1
df_w = n*(k-1)


for (i_edge in 1:length(target)-1){
  x= data.frame(unlist(z_target[,i_edge]),unlist(z_database[,i_edge]) )
  x_w_mean =  rowMeans(x)
  x_g_mean = mean(unlist(x))
  ss_t = sum(((x - x_g_mean)^2))
  ss_w = sum((x - (x_w_mean))^2)
  ss_b = ss_t - ss_w
  ms_b = ss_b / df_b
  ms_w = ss_w / df_w
  icc[i_edge] = (ms_b - ms_w) / (ms_b + ((k-1)*ms_w))
  
  
}

icc_mat_PD <- matrix(icc, nrow = 68, byrow = TRUE)

X=data.frame(theta= rowMeans(icc_mat_PD[,7:18]),alpha= rowMeans(icc_mat_PD[,19:33]),beta= rowMeans(icc_mat_PD[,34:84]), gamma= rowMeans(icc_mat_PD[,84:115]))


demo=read.csv('~/Documents/CAMCAN_outputs/CAMCAN_Analysis/standard_data.csv')
demo$CCID=paste('sub',demo$CCID, sep = '_')
ids=read.csv('~/Documents/CAMCAN_outputs/CAMCAN_Analysis/subject_codes.csv')
index=demo$CCID %in% ids$Ids
demo=demo[index,]

full_demo=read.csv('~/Documents/CAMCAN_outputs/approved_data.csv')
full_demo$CCID=paste('sub',full_demo$CCID, sep = '_')
index=full_demo$CCID %in% ids$Ids
full_demo=full_demo[index,]

psd_rest=read.csv('~/Documents/CAMCAN_outputs/CAMCAN_Analysis/PSD_justRest.csv', header = FALSE)
psd_task=read.csv('~/Documents/CAMCAN_outputs/CAMCAN_Analysis/PSD_justRest2.csv', header = FALSE)

aper_rest=read.csv('/Users/jason/Documents/CAMCAN_outputs/CAMCAN_Analysis/aperioidc_rest1.csv', header = FALSE)
aper_task=read.csv('~/Documents/CAMCAN_outputs/CAMCAN_Analysis/aperiodic_rest2.csv', header = FALSE)

# save aperiodic corrected data
list=1:68
roi_index= c(mapply(seq, 300*(list-1)+3, (300*(list-1)+81)))

ap_corr_psd_rest= log(psd_rest[,roi_index]) - log(aper_rest)
ap_corr_psd_task= log(psd_task[,roi_index]) - log(aper_task)

index_age= demo$Age >= 40 & demo$Age <= 78

z_target= t(scale(t(ap_corr_psd_rest[index_age,])))
z_database= t(scale(t(ap_corr_psd_task[index_age,])))
icc = c()


n = 370
k = 2
df_b = n-1
df_w = n*(k-1)


for (i_edge in 1:length(ap_corr_psd_rest)){
  x= data.frame(unlist(z_target[,i_edge]),unlist(z_database[,i_edge]) )
  x_w_mean =  rowMeans(x)
  x_g_mean = mean(unlist(x))
  ss_t = sum(((x - x_g_mean)^2))
  ss_w = sum((x - (x_w_mean))^2)
  ss_b = ss_t - ss_w
  ms_b = ss_b / df_b
  ms_w = ss_w / df_w
  icc[i_edge] = (ms_b - ms_w) / (ms_b + ((k-1)*ms_w))
  
  
}

icc_mat_camcan <- matrix(icc, nrow = 68, byrow = TRUE)

Xcam=data.frame(theta= rowMeans(icc_mat_camcan[,7:14]),alpha= rowMeans(icc_mat_camcan[,15:24]),beta= rowMeans(icc_mat_camcan[,25:58]), gamma= rowMeans(icc_mat_camcan[,59:79]))

diffcam=X-Xcam


#### diff in ICC between PD and CTLS
df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
colnames(df)[1]='region'
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'

someData= tidyr::tibble(df$region, rowMeans(diffcam), df$hemi)
colnames(someData)[2]='ICC'
colnames(someData)[1]='region'
colnames(someData)[3]='hemi'

someData$ICC[someData$ICC >0.2] =0.2
someData$ICC[someData$ICC < -0.2] = -0.2

ggplot(someData) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = `ICC`)) +
  scale_fill_gradient2(low = "#67309A", mid = "#FCF7F4", high = "#EC7A48", midpoint = 0.0, limits=c(-0.3, 0.3 )) +
  theme_void() 


ggsave('~/Documents/PD_fingerprinting/figure/SYLVAINCHECK_ICC_diff_based_on_camcan.pdf', device = "pdf", width=5, height=5, dpi=800)



someData$ICC[someData$ICC >0.1] =0.1
someData$ICC[someData$ICC < -0.2] = -0.2

ggplot(someData) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = `ICC`)) +
  scale_fill_gradient2(low = "#67309A", mid = "#FCF7F4", high = "#EC7A48", midpoint = 0.0, limits=c(-0.2, 0.1 )) +
  theme_void() 


ggsave('~/Documents/PD_fingerprinting/figure/SYLVAINCHECK_ICC_diff_based_on_camcan.pdf', device = "pdf", width=5, height=5, dpi=800)



#### diff in ICC between PD and CTLS
df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
df2=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_PD.csv', header = FALSE, stringsAsFactors = FALSE)
df2[,2:116]=df2[,2:116]-df[,2:116]


# Define X and Y data
DIFFOrig=data.frame(theta= rowMeans(df2[,7:18]),alpha= rowMeans(df2[,19:33]),beta= rowMeans(df2[,34:84]), gamma= rowMeans(df2[,84:116]))

cor.test(rowMeans(diffcam), rowMeans(DIFFOrig))
# correlation of 0.75 between control ICC

permuted_index= read.csv('~/Documents/CAMCAN_outputs/neuromaps/permuted_indexes_of_dk_atlas.csv')
permuted_index= permuted_index[,-1]
permuted_index=permuted_index+1

#gradient offset
orig=cor.test(rowMeans(diffcam), rowMeans(DIFFOrig)) # even larger effect for decoding 
permuted_corr=c()
for (i in 1001:2000){
  
  cor_temp=cor.test(rowMeans(diffcam), rowMeans(DIFFOrig)[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate < permuted_corr)/1000
# permuted p value for gradient = 0.00 !




deviation=read.csv( '~/Documents/PD_fingerprinting/QPN_allIDs_SumAbsDeviations_origminusap_DKatlasAVGs_PD_06192023.csv')


#gradient offset
orig=cor.test(rowMeans(diffcam), colMeans(deviation[,2:69])) # even larger effect for decoding 
permuted_corr=c()
for (i in 1001:2000){
  
  cor_temp=cor.test(rowMeans(diffcam), colMeans(deviation[,2:69])[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate < permuted_corr)/1000
# corr 0.679 p SPIN 0 


#
SVM=read.csv( '~/Documents/PD_fingerprinting/Results_from_SVM_class_of_HY_aperiodic_corrected_80_20.csv')
SVM=SVM[,-1]
cor.test(rowMeans(diffcam), colMeans(SVM)) # even larger effect for decoding 

SVM=read.csv( '~/Documents/PD_fingerprinting/Results_from_SVM_class_of_HY_aperiodic_corrected_70_30.csv')
SVM=SVM[,-1]
cor.test(rowMeans(diffcam), colMeans(SVM)) # even larger effect for decoding 

SVM=read.csv( '~/Documents/PD_fingerprinting/Results_from_SVM_class_of_HY_aperiodic_corrected_90_10.csv')
SVM=SVM[,-1]
cor.test(rowMeans(diffcam), colMeans(SVM)) # even larger effect for decoding 

#gradient offset
orig=cor.test(rowMeans(diffcam), colMeans(SVM)) # even larger effect for decoding 
permuted_corr=c()
for (i in 1001:2000){
  
  cor_temp=cor.test(rowMeans(diffcam), colMeans(SVM)[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate < permuted_corr)/1000
# permuted p value for gradient = 0.00 !

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")

data4reg=data.frame(SVM= colMeans(SVM), ICC=rowMeans(diffcam))
#data4reg= as.data.frame(scale(data4reg))
lm3=lm(SVM ~ ICC, data4reg)
summary(lm3)

ggplot(data4reg, aes(x=SVM , y = ICC, fill=cbbPalette[3])) + 
  geom_jitter(colour = cbbPalette[6]) + 
  stat_smooth(method = "lm", colour = 'black',fullrange = T, fill=cbbPalette[3]) +
  labs(title = paste("Adj R2 = ", signif(summary(lm3)$adj.r.squared, 5),
                     "Intercept =", signif(lm3$coef[[1]],5 ),
                     " Slope =", signif(lm3$coef[[2]], 5),
                     " P =", signif(summary(lm3)$coef[2,4], 5) )) + scale_fill_manual(values=cbbPalette[3])  + theme_classic2() +   xlab("decoding accuracy (%)") + ylab("delta ICC (camcan data)")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"), legend.position = "none") 

ggsave('~/Documents/PD_fingerprinting/figure/2023_Regression_SVM_ICC_CAMCAN_80_20.pdf', device = "pdf", width=5, height=5, dpi=800)



####

neuromaps= read.csv('~/Documents/PD_fingerprinting/neuromaps/receptor_data_scale033_full.csv')
cor.test(rowMeans(diffcam), neuromaps$func_grad_01)

data4plot= data.frame(fullband= rowMeans(diffcam), functiona_grad= neuromaps$func_grad_01)

lm3=lm(`functiona_grad` ~ fullband, data4plot)
summary(lm3)

ggplot(data4plot, aes(x=functiona_grad , y = fullband, fill=cbbPalette[6])) + 
  geom_jitter(colour = cbbPalette[6]) + 
  stat_smooth(method = "lm", colour = 'black',fullrange = T, fill=cbbPalette[6]) +
  labs(title = paste("Adj R2 = ", signif(summary(lm3)$adj.r.squared, 5),
                     "Intercept =", signif(lm3$coef[[1]],5 ),
                     " Slope =", signif(lm3$coef[[2]], 5),
                     " P =", signif(summary(lm3)$coef[2,4], 5) )) + scale_fill_manual(values=cbbPalette[4])  + theme_classic2() +   xlab("delta ICC camcan") + ylab("functional gradient")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"), legend.position = "none") 

ggsave('~/Documents/PD_fingerprinting/figure/2023_Regression_ICC_CAMCAN_functional_grad.pdf', device = "pdf", width=5, height=5, dpi=800)


permuted_index= read.csv('~/Documents/CAMCAN_outputs/neuromaps/permuted_indexes_of_dk_atlas.csv')
permuted_index= permuted_index[,-1]
permuted_index=permuted_index+1

#gradient offset
orig=cor.test(rowMeans(diffcam), neuromaps$func_grad_01)
permuted_corr=c()
for (i in 1:1000){
  
  cor_temp=cor.test(rowMeans(diffcam), neuromaps$func_grad_01[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000
# permuted p value for gradient = 0.0 !


# Define X and Y data
X=data.frame(broadband= rowMeans(diffcam))
Y = neuromaps[,c(7:25)]

corr_mat=corrplot::cor.mtest(cbind(X,Y))
r_matrix=cor(cbind(X,Y))
r_matrix=r_matrix[2:20, 1]
p_val=corr_mat$p
p_val=p_val[2:20,1]
p_corrected=matrix(p.adjust(p_val, 'fdr'), nrow = 1)
p_corrected_bin=p_corrected <0.05
colnames(p_corrected_bin)= colnames(neuromaps[,c(7:25)])
colnames(p_corrected)= colnames(neuromaps[,c(7:25)])

bf_map=r_matrix

for (j in 1:19){
  bf = BayesFactor::correlationBF(y = Y[,j], x = X[,1])
  bf_map[j]=exp(as.numeric(bf@bayesFactor[1]))
}


p_longData<-reshape2::melt(bf_map)
p_longData$r_vals= round(r_matrix, 2)
p_longData$value[p_longData$value>100]=100
p_longData$Var1= factor(colnames(neuromaps[,c(7:25)]),levels = c('D1',	'D2',	'DAT',	'X5HT1a',	'X5HT1b',	'X5HT2a',	'X5HT4',	'X5HT6',	'X5HTT',	'A4B2',	'M1',	'VAChT',	'GABAa',	'NMDA',	'mGluR5',	'NET',	'H3',	'CB1',	'MOR'))

ggplot(p_longData, aes(x = Var1, y = 1, fill=value)) + 
  geom_tile(color = "gray") +  
  scale_fill_gradient2(low = "#f5ec6c", mid = "white", high = "#F0792C", midpoint = 1.0, limits= c(0,100)) +
  labs(x=" ", y="", title="") + geom_text(aes(label=r_vals), size = 7.5) +
  theme_void() + theme(axis.text.x=element_text(size=15, angle=0, vjust=0.3),
                       axis.text.y=element_text(size=15),
                       plot.title=element_text(size=15))

ggsave('~/Documents/PD_fingerprinting/figure/2023_NEUROMAPS_bayesfactor_camcan.pdf', device = "pdf", width=20, height=2, dpi=800)




#gradient offset
orig=cor.test(rowMeans(diffcam), neuromaps$X5HT4)
permuted_corr=c()
for (i in 5001:6000){
  
  cor_temp=cor.test(rowMeans(diffcam), neuromaps$X5HT4[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.001

#gradient offset
orig=cor.test(rowMeans(diffcam), neuromaps$CB1)
permuted_corr=c()
for (i in 6001:7000){
  
  cor_temp=cor.test(rowMeans(diffcam), neuromaps$CB1[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.002

#gradient offset
orig=cor.test(rowMeans(diffcam), neuromaps$NET)
permuted_corr=c()
for (i in 7001:8000){
  
  cor_temp=cor.test(rowMeans(diffcam), neuromaps$NET[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate < permuted_corr)/1000 #0.00



#gradient offset
orig=cor.test(rowMeans(diffcam), neuromaps$MOR)
permuted_corr=c()
for (i in 8001:9000){
  
  cor_temp=cor.test(rowMeans(diffcam), neuromaps$MOR[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.001

#gradient offset
orig=cor.test(rowMeans(diffcam), neuromaps$X5HT2a)
permuted_corr=c()
for (i in 8001:9000){
  
  cor_temp=cor.test(rowMeans(diffcam), neuromaps$X5HT2a[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.004

#gradient offset
orig=cor.test(rowMeans(diffcam), neuromaps$X5HT1a)
permuted_corr=c()
for (i in 8001:9000){
  
  cor_temp=cor.test(rowMeans(diffcam), neuromaps$X5HT1a[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.001


#gradient offset
orig=cor.test(rowMeans(diffcam), neuromaps$X5HTT)
permuted_corr=c()
for (i in 8001:9000){
  
  cor_temp=cor.test(rowMeans(diffcam), neuromaps$X5HTT[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.002


#gradient offset
orig=cor.test(rowMeans(diffcam), neuromaps$D1)
permuted_corr=c()
for (i in 8001:9000){
  
  cor_temp=cor.test(rowMeans(diffcam), neuromaps$D1[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.004

#gradient offset
orig=cor.test(rowMeans(diffcam), neuromaps$D2)
permuted_corr=c()
for (i in 8001:9000){
  
  cor_temp=cor.test(rowMeans(diffcam), neuromaps$D2[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

sum(orig$estimate > permuted_corr)/1000 #0.035


p.adjust(c(,0.004,0.035), 'fdr')



Y = neuromaps[,7:30]
Y2= scale(Y)
Y2= as.data.frame(Y2)
df=read.csv('~/Documents/Alex_fingerprinting/PSD_ICC_orig_PD_new_PKD2.csv', header = FALSE, stringsAsFactors = FALSE)
colnames(df)[1]='region'
df_plot=df[,1:2]
df_plot$hemi =''
df_plot$hemi[seq(2,68,2)] ='right'
df_plot$hemi[seq(1,67,2)] ='left'
df_plot$receptor=Y2$D1

someData2= df_plot
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

someData2$receptor[someData2$receptor>2]=2
someData2$receptor[someData2$receptor< -2]= -2

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = receptor)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'rocket', limits = c(-2, 2))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/figure/2023_DEC_NEUROMAPS_D1_receptor_map.pdf', device = "pdf")

df_plot$receptor=Y2$D2

someData2= df_plot
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

someData2$receptor[someData2$receptor>2]=2
someData2$receptor[someData2$receptor< -2]= -2

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = receptor)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'rocket', limits = c(-2, 2))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/figure/2023_DEC_NEUROMAPS_D2_receptor_map.pdf', device = "pdf")



df_plot$receptor=rowMeans(Y2[,c(9,10)])

someData2= df_plot
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

someData2$receptor[someData2$receptor>2]=2
someData2$receptor[someData2$receptor< -2]= -2

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = receptor)) +
  #scale_fill_distiller(palette = "RdBu"
  #                     , limits = c(0.4, 0.9))+
  viridis::scale_fill_viridis(option = 'rocket', limits = c(-2, 2))+ theme_void() 

ggsave('~/Documents/PD_fingerprinting/figure/2023_DEC_NEUROMAPS_Dopamine_receptor_map.pdf', device = "pdf")



### Leave one our cross

predictions=read.csv( '~/Documents/PD_fingerprinting/2024_SVM_HY_aperiodic_corrected_LOOCV.csv')
predictions= predictions[,-1]

cor.test(rowMeans(predictions), rowMeans(diffcam) )

# 0.55


permuted_index= read.csv('~/Documents/CAMCAN_outputs/neuromaps/permuted_indexes_of_dk_atlas.csv')
permuted_index= permuted_index[,-1]
permuted_index=permuted_index+1

#gradient offset
orig=cor.test(rowMeans(predictions), rowMeans(diffcam) )
permuted_corr=c()
for (i in 3001:4000){
  
  cor_temp=cor.test(rowMeans(predictions), rowMeans(diffcam)[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

(sum(orig$estimate < permuted_corr)+1)/1001
# permuted p value for gradient < 0.001




```



```{r SVM to predict HY LOOCV ROI}

cbbPalette <- c( "#90319D","#E25987","#FFBF00","#3A3AA4", "#31CD71", "#F0792C", "#6C3ABF")
# read data and compute data for demographic table
data=read.csv('~/Documents/PD_fingerprinting/QPN_demo_compiled.csv', stringsAsFactors = FALSE)

target= read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_corrected_target.csv' )

database= read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/NEW_aperiodic_corrected_database.csv' )

target=target[,-1]
database=database[,-1]

predictions= matrix(,nrow = 68, ncol = 100)

for (j in 1:68){

roi_index= (115*(j-1)+1):(115*(j-1)+115)

target_LSP= target[,roi_index]
database_LSP= database[,roi_index]
target_LSP= (target_LSP+database_LSP)/2


PSD=target_LSP[!is.na(data$Hoehn.and.Yahr.score),]
data2=data[!is.na(data$Hoehn.and.Yahr.score),]

data2$HoehnYarr_bin= data2$Hoehn.and.Yahr.score >1.5
data2$HoehnYarr_bin = as.factor(data2$HoehnYarr_bin)


for (k in 1:100){
  
  prediction=c()
  for (i in 1:46){
    
      datatest=PSD[i,]
      datatest$HoehnYarr_bin= as.numeric(data2$Hoehn.and.Yahr.score[i] >1.5)
      
      PSD2= PSD[-i,]
      data3=data2[-i,]
      
      data_HYpos= PSD2[data3$Hoehn.and.Yahr.score >1.5,]
      data_HYneg= PSD2[data3$Hoehn.and.Yahr.score <=1.5,]

      ids_pos=sample(nrow(data_HYpos),12)
      ids_neg= sample(nrow(data_HYneg),12)

      datatrain= rbind(data_HYpos[ids_pos[1:12],], data_HYneg[ids_neg[1:12],])
      datatrain$HoehnYarr_bin= c(rep(1 ,12), rep(0, 12))
      datatrain$HoehnYarr_bin= as.factor(datatrain$HoehnYarr_bin)

      svm_model=e1071::svm(HoehnYarr_bin ~., data= datatrain, kernel = "linear", cost = 1)

      pred <- predict(svm_model,datatest)
      prediction[i]=sum(pred==datatest$HoehnYarr_bin)
  }
  
  predictions[j,k]=sum(prediction)/46

}
print(j)
}

write.csv(predictions, '~/Documents/PD_fingerprinting/2024_SVM_HY_aperiodic_corrected_LOOCV.csv')
#prediction= as.data.frame(prediction)

predictions=read.csv( '~/Documents/PD_fingerprinting/2024_SVM_HY_aperiodic_corrected_LOOCV.csv')
predictions= predictions[,-1]

#### diff in ICC between PD and CTLS
df=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_controls.csv', header = FALSE, stringsAsFactors = FALSE)
df2=read.csv('~/Documents/PD_fingerprinting/new_analysis_Nov2022/2023correctedspectra_ICC_PD.csv', header = FALSE, stringsAsFactors = FALSE)
df2[,2:116]=df2[,2:116]-df[,2:116]

# Define X and Y data
X=data.frame(theta= rowMeans(df2[,7:18]),alpha= rowMeans(df2[,19:33]),beta= rowMeans(df2[,34:84]), gamma= rowMeans(df2[,84:116]))

ICC=rowMeans(X)

cor.test(rowMeans(predictions), ICC )


permuted_index= read.csv('~/Documents/CAMCAN_outputs/neuromaps/permuted_indexes_of_dk_atlas.csv')
permuted_index= permuted_index[,-1]
permuted_index=permuted_index+1

#gradient offset
orig=cor.test(rowMeans(predictions), ICC )
permuted_corr=c()
for (i in 3001:4000){
  
  cor_temp=cor.test(rowMeans(predictions), ICC[permuted_index[,i]])
  permuted_corr= c(permuted_corr, cor_temp$estimate)
  
}

(sum(orig$estimate < permuted_corr)+1)/1001
# permuted p value for gradient < 0.001


df=read.csv('~/Documents/Alex_fingerprinting/PSD_ICC_orig_PD_new_PKD2.csv', header = FALSE, stringsAsFactors = FALSE)
colnames(df)[1]='region'
df=df[,1:2]
df$hemi =''
df$hemi[seq(2,68,2)] ='right'
df$hemi[seq(1,67,2)] ='left'
df$ACC=rowMeans(predictions)

df$ACC[df$ACC < 0.5] =0.5
df$ACC[df$ACC > 0.73] =0.73

someData2= df
colnames(someData2)[2]='Fingerprinting accuracy'
colnames(someData2)[1]='region'
colnames(someData2)[3]='hemi'

ggplot(someData2) +
  geom_brain(atlas = dk, 
             position = position_brain(hemi ~ side),
             aes(fill = `ACC`)) +
   scale_fill_gradient2(low = "#ECECEC", mid = "#ECECEC", high = "#E25987", midpoint = 0.50, limits=c(0.5,0.73), breaks= seq(0.5, 0.73)) +
  theme_void() 

ggsave('~/Documents/PD_fingerprinting/figure/2024_decode_HY_ROI_aperiodic_corrected_LOOCV.pdf', device = "pdf")


data4reg=data.frame(SVM= rowMeans(predictions), ICC=ICC)
#data4reg= as.data.frame(scale(data4reg))
lm3=lm(SVM ~ ICC, data4reg)
summary(lm3)

ggplot(data4reg, aes(x=SVM , y = ICC, fill=cbbPalette[3])) + 
  geom_jitter(colour = cbbPalette[6]) + 
  stat_smooth(method = "lm", colour = 'black',fullrange = T, fill=cbbPalette[3]) +
  labs(title = paste("Adj R2 = ", signif(summary(lm3)$adj.r.squared, 5),
                     "Intercept =", signif(lm3$coef[[1]],5 ),
                     " Slope =", signif(lm3$coef[[2]], 5),
                     " P =", signif(summary(lm3)$coef[2,4], 5) )) + scale_fill_manual(values=cbbPalette[3])  + theme_classic2() +   xlab("decoding accuracy (%)") + ylab("ICC")+
  theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"), legend.position = "none") 

ggsave('~/Documents/PD_fingerprinting/figure/2024_Regression_SVM_ICC_aperiodic_corrected_LOOCV.pdf', device = "pdf", width=5, height=5, dpi=800)



```
